# Part 2 — Group Presentation & Notebook

**Group members:** 

- Dargys Perez : `Data Engineer`
  
- Cecilia Back : `Data Analyst`

- Marta Bielow : `Accounting Manager`
  
- Jessika Rosen : `Head of Finance` – (accountable for regulatory compliance 
and overall financial processes, not directly involved in the operational analysis meeting.)

## Data Quality Issues 

**Compliance with the 10-day rule (delivery to invoice) was the focus of the work meeting.**

*The following issues were raised:*
- Why does the delivery_confirmed_date in Deliveries.csv (originating from the logistics system/TMS) contain multiple date formats?
- What is the current situation regarding the time gap between delivery_confirmed_date and invoice_date? 
- Based on available historical data, how well are we complying with the 10-day rule today?

In [14]:
# using pandas for data analysis
import pandas as pd

In [15]:
# load the relevant data for the 10 rules analysis
invoice_line = pd.read_csv("invoice_line.csv")
deliveries = pd.read_csv("deliveries.csv")
order_line = pd.read_csv("order_line.csv")

In [16]:
invoice_line['invoice_date']

0      2027-02-03
1      2027-02-07
2      2027-03-09
3      2027-02-03
4      2027-02-07
          ...
98     2027-03-10
99     2027-03-09
100    2027-02-14
101    2027-03-05
102    2027-03-09
Name: invoice_date, Length: 103, dtype: str

In [4]:
deliveries['delivery_confirm_date']

0              2027-02-10
1              2027-01-13
2              2027-03-03
3     2027-03-19T11:33:00
4              19/03/2027
5              2027-02-19
6              2027-02-19
7              2027-03-05
8              2027-03-22
9              2027-02-08
10             2027-01-19
11             2027-01-17
12             2027-02-04
13             2027-02-02
14             2027-03-03
15             2027-01-19
16             2027-02-28
17             2027-02-03
18             2027-01-29
19    2027-03-02T11:01:00
20            24 Mar 2027
21             2027-02-11
22             2027-02-07
23             2027-02-02
24             2027-02-15
25             13-02-2027
26             2027-01-25
27             2027-02-07
28             2027-01-28
29             2027-03-01
30    2027-02-13T11:36:00
31             2027-02-25
32             2027-01-18
33             2027-03-08
34             2027-01-31
35    2027-02-18T12:09:00
36             2027-01-26
37             2027-03-19
38             2027-02-10
39             2027-01-29
40             2027-01-21
41             2027-02-23
42             2027-03-08
43             2027-02-27
44             2027-03-16
45             2027-02-05
46             2027-01-31
47             2027-02-13
48             2027-01-31
49             2027-02-16
50             2027-02-16
51             2027-01-08
52             21/01/2027
53             2027-03-06
54             2027-03-12
Name: delivery_confirm_date, dtype: str

In [5]:
deliveries.dtypes

delivery_confirm_id      str
order_id                 str
delivery_confirm_date    str
delivery_country         str
dtype: object

In [ ]:
invoice_line.dtypes

In [47]:
invoice_line.groupby("order_id")["invoice_date"].nunique().value_counts()

invoice_date
1    50
Name: count, dtype: int64

In [48]:
invoice_line.groupby("order_id")["invoice_date"].value_counts()

order_id         invoice_date
ORD-2026-131279  2027-02-07      2
ORD-2026-146236  2027-02-10      2
ORD-2026-222382  2027-02-14      1
ORD-2026-339139  2027-02-24      2
ORD-2026-447001  2027-02-07      2
ORD-2026-483219  2027-02-06      3
ORD-2026-529027  2027-02-08      2
ORD-2026-543670  2027-02-14      3
ORD-2026-620917  2027-02-11      2
ORD-2026-865441  2027-02-01      1
ORD-2026-882286  2027-03-09      2
ORD-2026-990340  2027-02-03      3
ORD-2027-116776  2027-03-10      3
ORD-2027-126344  2027-03-17      3
ORD-2027-128047  2027-02-03      1
ORD-2027-131033  2027-02-15      3
ORD-2027-152306  2027-03-09      4
ORD-2027-195450  2027-02-03      1
ORD-2027-259085  2027-02-08      2
ORD-2027-278275  2027-03-25      1
ORD-2027-296460  2027-02-17      1
ORD-2027-315951  2027-03-20      2
ORD-2027-340184  2027-02-21      6
ORD-2027-346967  2027-02-17      1
ORD-2027-361984  2027-03-28      1
ORD-2027-376129  2027-03-26      2
ORD-2027-419673  2027-03-30      1
ORD-2027-429920  2027-03-29      4
ORD-2027-445827  2027-03-05      2
ORD-2027-449701  2027-03-09      3
ORD-2027-483237  2027-02-18      3
ORD-2027-519359  2027-02-04      1
ORD-2027-599775  2027-03-17      1
ORD-2027-607214  2027-03-16      2
ORD-2027-610481  2027-03-13      1
ORD-2027-612463  2027-03-16      1
ORD-2027-632086  2027-03-22      1
ORD-2027-684015  2027-02-22      1
ORD-2027-705043  2027-02-06      2
ORD-2027-729651  2027-03-18      2
ORD-2027-778397  2027-02-25      2
ORD-2027-850022  2027-03-10      3
ORD-2027-874942  2027-03-06      2
ORD-2027-881543  2027-03-24      4
ORD-2027-901318  2027-03-05      1
ORD-2027-911031  2027-02-16      1
ORD-2027-938226  2027-03-30      1
ORD-2027-943881  2027-02-18      3
ORD-2027-956035  2027-02-07      3
ORD-2027-966069  2027-02-17      2
Name: count, dtype: int64

In [49]:
#Normalize invoice_line data to one row per order_id
invoice_order = (
    invoice_line
    .drop_duplicates(subset=["order_id"])
    [["order_id", "invoice_date"]]
)

In [ ]:
# Cleaning Order_Line file 
order_order = (
    order_line
    .drop_duplicates(subset=["order_id"])
    [["order_id", "order_date"]]
    )

In [19]:
order_order

            order_id  order_date
0    ORD-2026-339139  2026-12-07
1    ORD-2027-131033  2027-01-15
2    ORD-2027-259085  2027-01-19
3    ORD-2027-152306  27/01/2027
4    ORD-2027-278275  2027-02-05
..               ...         ...
87   ORD-2026-865441  2026-12-08
90   ORD-2026-882286  2026-12-29
99   ORD-2026-529027  2026-12-07
108  ORD-2027-315951  2027-02-04
115  ORD-2027-346967  2027-01-05

[61 rows x 2 columns]

In [20]:
# Ensure that the data is cleaned from duplicates.
invoice_order.value_counts()

order_id         invoice_date
ORD-2027-128047  2027-02-03      1
ORD-2026-131279  2027-02-07      1
ORD-2027-449701  2027-03-09      1
ORD-2027-195450  2027-02-03      1
ORD-2027-956035  2027-02-07      1
ORD-2026-222382  2027-02-14      1
ORD-2026-483219  2027-02-06      1
ORD-2027-874942  2027-03-06      1
ORD-2027-705043  2027-02-06      1
ORD-2027-296460  2027-02-17      1
ORD-2027-340184  2027-02-21      1
ORD-2027-850022  2027-03-10      1
ORD-2027-881543  2027-03-24      1
ORD-2027-612463  2027-03-16      1
ORD-2027-632086  2027-03-22      1
ORD-2027-126344  2027-03-17      1
ORD-2026-339139  2027-02-24      1
ORD-2026-146236  2027-02-10      1
ORD-2027-943881  2027-02-18      1
ORD-2027-729651  2027-03-18      1
ORD-2027-483237  2027-02-18      1
ORD-2027-445827  2027-03-05      1
ORD-2027-519359  2027-02-04      1
ORD-2027-131033  2027-02-15      1
ORD-2027-684015  2027-02-22      1
ORD-2027-361984  2027-03-28      1
ORD-2027-966069  2027-02-17      1
ORD-2026-620917  2027-02-11      1
ORD-2027-778397  2027-02-25      1
ORD-2027-429920  2027-03-29      1
ORD-2027-599775  2027-03-17      1
ORD-2027-259085  2027-02-08      1
ORD-2026-865441  2027-02-01      1
ORD-2026-543670  2027-02-14      1
ORD-2026-529027  2027-02-08      1
ORD-2026-990340  2027-02-03      1
ORD-2027-116776  2027-03-10      1
ORD-2027-607214  2027-03-16      1
ORD-2027-376129  2027-03-26      1
ORD-2027-152306  2027-03-09      1
ORD-2027-419673  2027-03-30      1
ORD-2026-447001  2027-02-07      1
ORD-2027-346967  2027-02-17      1
ORD-2027-911031  2027-02-16      1
ORD-2026-882286  2027-03-09      1
ORD-2027-315951  2027-03-20      1
ORD-2027-938226  2027-03-30      1
ORD-2027-610481  2027-03-13      1
ORD-2027-278275  2027-03-25      1
ORD-2027-901318  2027-03-05      1
Name: count, dtype: int64

In [21]:
#Join datasets
df = invoice_order.merge(
    deliveries,
    on="order_id",
    how="left"
)

In [ ]:
# Check for the results after joining the datasets.
df

,order_id,invoice_date,delivery_confirm_id,delivery_confirm_date,delivery_country
0,ORD-2027-128047,2027-02-03,CONF-166306,2027-01-26,Belgium
1,ORD-2026-131279,2027-02-07,CONF-929529,2027-02-02,Netherlands
2,ORD-2027-449701,2027-03-09,CONF-997937,2027-03-03,Italy
3,ORD-2027-195450,2027-02-03,CONF-409355,2027-01-21,France
4,ORD-2027-956035,2027-02-07,CONF-201833,2027-01-18,Netherlands
5,ORD-2026-222382,2027-02-14,CONF-367038,2027-01-31,Poland
6,ORD-2026-483219,2027-02-06,CONF-560965,2027-01-08,Netherlands
7,ORD-2027-874942,2027-03-06,CONF-416562,2027-02-27,Sweden
8,ORD-2027-705043,2027-02-06,CONF-142442,2027-01-29,Italy
9,ORD-2027-296460,2027-02-17,CONF-747653,2027-02-10,France
10,ORD-2027-340184,2027-02-21,CONF-831485,2027-02-03,Sweden
11,ORD-2027-850022,2027-03-10,CONF-116922,2027-02-16,Poland
12,ORD-2027-881543,2027-03-24,CONF-699281,2027-03-06,Germany
13,ORD-2027-612463,2027-03-16,CONF-837992,2027-03-02T11:01:00,Italy
14,ORD-2027-632086,2027-03-22,CONF-629017,2027-02-23,Germany
15,ORD-2027-126344,2027-03-17,CONF-381172,2027-03-12,France
16,ORD-2026-339139,2027-02-24,CONF-871248,2027-02-05,France
17,ORD-2026-146236,2027-02-10,CONF-658572,21/01/2027,Belgium
18,ORD-2027-943881,2027-02-18,CONF-899842,13-02-2027,Netherlands
19,ORD-2027-729651,2027-03-18,CONF-914547,2027-02-18T12:09:00,Germany
20,ORD-2027-483237,2027-02-18,CONF-273594,2027-02-13T11:36:00,Belgium
21,ORD-2027-445827,2027-03-05,CONF-885054,2027-02-25,Belgium
22,ORD-2027-519359,2027-02-04,CONF-342205,2027-01-25,Germany
23,ORD-2027-131033,2027-02-15,CONF-170024,2027-01-31,Belgium
24,ORD-2027-684015,2027-02-22,CONF-175182,2027-02-13,Germany
25,ORD-2027-361984,2027-03-28,CONF-101069,2027-03-19T11:33:00,Germany
26,ORD-2027-966069,2027-02-17,CONF-941444,2027-02-10,Germany
27,ORD-2026-620917,2027-02-11,CONF-973773,2027-01-19,Germany
28,ORD-2027-778397,2027-02-25,CONF-477680,2027-02-19,Poland
29,ORD-2027-429920,2027-03-29,CONF-575037,2027-03-19,Sweden
30,ORD-2027-599775,2027-03-17,CONF-260684,2027-03-08,Belgium
31,ORD-2027-259085,2027-02-08,CONF-654641,2027-02-02,France
32,ORD-2026-865441,2027-02-01,CONF-650282,2027-01-13,France
33,ORD-2026-543670,2027-02-14,CONF-512030,2027-01-29,France
34,ORD-2026-529027,2027-02-08,CONF-159878,2027-01-31,France
35,ORD-2026-990340,2027-02-03,CONF-933014,2027-01-19,Germany
36,ORD-2027-116776,2027-03-10,CONF-198879,2027-03-05,Netherlands
37,ORD-2027-607214,2027-03-16,CONF-423844,2027-02-19,Germany
38,ORD-2027-376129,2027-03-26,CONF-643473,2027-03-16,Belgium
39,ORD-2027-152306,2027-03-09,CONF-960121,2027-03-03,Netherlands
40,ORD-2027-419673,2027-03-30,CONF-993839,24 Mar 2027,Poland
41,ORD-2026-447001,2027-02-07,CONF-579202,2027-01-28,Netherlands
42,ORD-2027-346967,2027-02-17,CONF-526176,2027-02-08,Netherlands
43,ORD-2027-911031,2027-02-16,CONF-535742,2027-02-11,Germany
44,ORD-2026-882286,2027-03-09,CONF-343576,2027-02-15,France
45,ORD-2027-315951,2027-03-20,CONF-252778,2027-03-01,France
46,ORD-2027-938226,2027-03-30,CONF-244615,2027-03-22,Sweden
47,ORD-2027-610481,2027-03-13,CONF-963542,2027-03-08,Poland
48,ORD-2027-278275,2027-03-25,CONF-406108,19/03/2027,Netherlands
49,ORD-2027-901318,2027-03-05,CONF-523787,2027-02-28,Poland

In [ ]:
# LEFT JOIN with the Order table to include the order_date column in the results.
df1 = order_order.merge(
    df,
    on= "order_id",
    how="left"
)

In [ ]:
#Checking for the results
df1

,order_id,order_date,invoice_date,delivery_confirm_id,delivery_confirm_date,delivery_country
0,ORD-2026-339139,2026-12-07,2027-02-24,CONF-871248,2027-02-05,France
1,ORD-2027-131033,2027-01-15,2027-02-15,CONF-170024,2027-01-31,Belgium
2,ORD-2027-259085,2027-01-19,2027-02-08,CONF-654641,2027-02-02,France
3,ORD-2027-152306,27/01/2027,2027-03-09,CONF-960121,2027-03-03,Netherlands
4,ORD-2027-278275,2027-02-05,2027-03-25,CONF-406108,19/03/2027,Netherlands
...,...,...,...,...,...,...
56,ORD-2026-865441,2026-12-08,2027-02-01,CONF-650282,2027-01-13,France
57,ORD-2026-882286,2026-12-29,2027-03-09,CONF-343576,2027-02-15,France
58,ORD-2026-529027,2026-12-07,2027-02-08,CONF-159878,2027-01-31,France
59,ORD-2027-315951,2027-02-04,2027-03-20,CONF-252778,2027-03-01,France
60,ORD-2027-346967,2027-01-05,2027-02-17,CONF-526176,2027-02-08,Netherlands

In [31]:
#Convert to datetime
df1["invoice_date"] = pd.to_datetime(df1["invoice_date"])

In [52]:
# the delivery_confirm_date has data quality issues, the date is given in differents formats and I need first to normalize.
df1["delivery_confirm_date"] = pd.to_datetime(
    df1["delivery_confirm_date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [53]:
#Calculate the date difference
df1["days_diff"] = (df1["invoice_date"] - df1["delivery_confirm_date"]).dt.days

#Categorize the result
df1["status"] = "Fulfill 10-day-rule"
df1.loc[df1["days_diff"] > 10, "status"] = "Late"
df1.loc[df1["days_diff"] < 0, "status"] = "Negative date-diff"
df1.loc[df1["days_diff"].isna(), "status"] = "Missing"

df1["status"].value_counts()

status
Fulfill 10-day-rule    22
Late                   16
Negative date-diff     12
Missing                11
Name: count, dtype: int64

In [44]:
summary = pd.DataFrame({
    "count": df1["status"].value_counts(),
    "percent": (df1["status"].value_counts(normalize=True) * 100).round(2)
})

print(summary)

                     count  percent
status
Fulfill 10-day-rule     22    36.07
Late                    16    26.23
Negative date-diff      12    19.67
Missing                 11    18.03

In [40]:
# How the "days_diff" are distributed in the dataset.
df1["days_diff"].value_counts().sort_index()

days_diff
-261.0    1
-259.0    1
-227.0    2
-176.0    1
-166.0    1
-143.0    1
-139.0    1
-71.0     1
-67.0     1
-54.0     1
-9.0      1
 4.0      1
 5.0      3
 6.0      6
 7.0      1
 8.0      6
 9.0      1
 10.0     4
 13.0     1
 14.0     1
 15.0     2
 16.0     1
 19.0     1
 20.0     2
 22.0     2
 23.0     1
 25.0     1
 27.0     2
 40.0     1
 76.0     1
Name: count, dtype: int64

In [ ]:
# Sorting out the orders with negative day_diff.
df1[df1["status"] == "Negative date_diff"]

Empty DataFrame
Columns: [order_id, order_date, invoice_date, delivery_confirm_id, delivery_confirm_date, delivery_country, days_diff, status]
Index: []

## Data Quality Findings – Delivery vs Invoice Dates

An analysis of the time difference between delivery_confirmed_date and invoice_date identified a number of cases with negative values, indicating that the invoice date precedes the delivery confirmation date.

**A subset of these cases was investigated manually in the source CSV files:**.<br>

*- Several records were confirmed to be data quality issues, primarily caused by:*.<br>
- Inconsistent or incorrect date formats.<br>
- Incorrectly recorded delivery dates.<br>
  
*- Other records could not be conclusively explained based on available data. Possible explanations include:* <br>

- Delayed registration of delivery confirmations in the logistics system (TMS).<br>
- Differences in business process (e.g. invoicing prior to delivery).<br>
- Integration or timing discrepancies between systems.<br>

*Further clarification would require:*
- Validation of business rules for invoicing vs delivery.<br>
- Review of source system definitions and event timestamps.<br>