# Part 2 — Group Presentation & Notebook

**Group members:** 

- Dargys Perez : `Data Engineer`
  
- Jessika Rosen : `Accounting Manager`
  
- Cecilia Back : `Data Analyst`

- Marta Bielow : `Accounting Manager`

**The 10-day rule**

From the date the customer order has been delivered, the invoice must be issued within 10 days since the delivery date. (invoice_date(invoice_line) - delivered_date(delivery_confirm_date/deliveries) <= 10)

In [1]:
# using pandas for data analysis
import pandas as pd

In [2]:
# load the relevant data for the 10 rules analysis
invoice_line = pd.read_csv("invoice_line.csv")
deliveries = pd.read_csv("deliveries.csv")
customers = pd.read_csv("customers.csv")

In [3]:
invoice_line['invoice_date']

0      2027-02-03
1      2027-02-07
2      2027-03-09
3      2027-02-03
4      2027-02-07
          ...
98     2027-03-10
99     2027-03-09
100    2027-02-14
101    2027-03-05
102    2027-03-09
Name: invoice_date, Length: 103, dtype: str

In [4]:
deliveries['delivery_confirm_date']

0              2027-02-10
1              2027-01-13
2              2027-03-03
3     2027-03-19T11:33:00
4              19/03/2027
5              2027-02-19
6              2027-02-19
7              2027-03-05
8              2027-03-22
9              2027-02-08
10             2027-01-19
11             2027-01-17
12             2027-02-04
13             2027-02-02
14             2027-03-03
15             2027-01-19
16             2027-02-28
17             2027-02-03
18             2027-01-29
19    2027-03-02T11:01:00
20            24 Mar 2027
21             2027-02-11
22             2027-02-07
23             2027-02-02
24             2027-02-15
25             13-02-2027
26             2027-01-25
27             2027-02-07
28             2027-01-28
29             2027-03-01
30    2027-02-13T11:36:00
31             2027-02-25
32             2027-01-18
33             2027-03-08
34             2027-01-31
35    2027-02-18T12:09:00
36             2027-01-26
37             2027-03-19
38             2027-02-10
39             2027-01-29
40             2027-01-21
41             2027-02-23
42             2027-03-08
43             2027-02-27
44             2027-03-16
45             2027-02-05
46             2027-01-31
47             2027-02-13
48             2027-01-31
49             2027-02-16
50             2027-02-16
51             2027-01-08
52             21/01/2027
53             2027-03-06
54             2027-03-12
Name: delivery_confirm_date, dtype: str

In [5]:
deliveries.dtypes

delivery_confirm_id      str
order_id                 str
delivery_confirm_date    str
delivery_country         str
dtype: object

In [6]:
invoice_line.dtypes

invoice_line_id            str
invoice_id                 str
invoice_date               str
invoice_type               str
order_id                   str
product_id                 str
product_description        str
quantity                 int64
uom                        str
unit_price             float64
currency                   str
line_amount            float64
vat_rate               float64
vat_amount             float64
total_amount           float64
invoice_status             str
invoice_ref                str
vat_category_code          str
dtype: object

In [7]:
invoice_line.tail()

,invoice_line_id,invoice_id,invoice_date,invoice_type,order_id,product_id,product_description,quantity,uom,unit_price,currency,line_amount,vat_rate,vat_amount,total_amount,invoice_status,invoice_ref,vat_category_code
98,IL-001,INV-2027-642637,2027-03-10,invoice,ORD-2027-850022,PROD-192837,Droxel 65W GaN Charger,86,pcs,28.4,EUR,2442.4,0.0,0.00,2442.40,issued,NaN,AE
99,IL-003,INV-2027-267919,2027-03-09,invoice,ORD-2027-449701,PROD-461829,Plonex Webcam 1080p Pro,36,pcs,44.0,EUR,1584.0,0.0,0.00,1584.00,issued,NaN,AE
100,IL-001,INV-2027-990042,2027-02-14,invoice,ORD-2026-543670,PROD-192837,Droxel 65W GaN Charger,48,pcs,28.4,EUR,1363.2,19.0,259.01,1622.21,issued,NaN,S
101,IL-001,INV-2027-140410,2027-03-05,invoice,ORD-2027-901318,PROD-639182,Blipcore Wireless Adapter AC1200,42,pcs,22.8,EUR,957.6,0.0,0.00,957.60,issued,NaN,AE
102,IL-001,INV-2027-226551,2027-03-09,invoice,ORD-2027-152306,PROD-738291,Quorvex 2TB NVMe SSD M.2,83,pcs,112.5,EUR,9337.5,0.0,0.00,9337.50,cancelled,NaN,AE

In [6]:
customers.tail()

,Customer ID,Name,Customer type,Registration no,VAT no,City,Country,Registration date,Updated date
10,CUST-599370,Nexivo Solutions SARL,business,FR22445566778,FR22445566778,Paris,France,2014-08-07,2019-09-28
11,CUST-349362,Vektaro Sverige AB,business,SE556771234501,SE556771234501,Stockholm,SE,2022-07-25,2025-02-05
12,CUST-365005,Blipware Systems GmbH,business,DE445523901,DE 44552390,Munich,Deutschland,2016-04-12,2016-09-05
13,CUST-302511,Fomtec Vertriebs GmbH,business,DE889967345,NaN,Dusseldorf,DE,2017-06-08,2021-02-13
14,CUST-741029,Plonix Distributie BV,business,NL553344556B01,NaN,Utrecht,NLD,2011-10-26,2016-05-21

Address at least one concrete data quality issue found in the datasets

In [20]:
#Join datasets
df = invoice_line.merge(
    deliveries,
    on="order_id",
    how="left"
)

In [21]:
#Convert to datetime
df["invoice_date"] = pd.to_datetime(df["invoice_date"])

In [22]:
# the delivery_confirm_date has data quality issues, the date is given in differents formats and I need first to normalize.
df["delivery_confirm_date"] = pd.to_datetime(
    df["delivery_confirm_date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [23]:
# I wanted to check if the datatypes where compatible with each other.
df.dtypes

invoice_line_id                     str
invoice_id                          str
invoice_date             datetime64[us]
invoice_type                        str
order_id                            str
product_id                          str
product_description                 str
quantity                          int64
uom                                 str
unit_price                      float64
currency                            str
line_amount                     float64
vat_rate                        float64
vat_amount                      float64
total_amount                    float64
invoice_status                      str
invoice_ref                         str
vat_category_code                   str
delivery_confirm_id                 str
delivery_confirm_date    datetime64[us]
delivery_country                    str
dtype: object

>Note: As we see the invoice_date and  delivery_confirm_date are both in the same format, ready for the next step

In [12]:
df["delivery_confirm_date"].tolist()

[Timestamp('2027-10-02 00:00:00'),
 Timestamp('2027-01-13 00:00:00'),
 Timestamp('2027-03-03 00:00:00'),
 Timestamp('2027-03-03 00:00:00'),
 Timestamp('2027-03-03 00:00:00'),
 Timestamp('2027-03-19 11:33:00'),
 Timestamp('2027-03-19 00:00:00'),
 Timestamp('2027-02-19 00:00:00'),
 Timestamp('2027-02-19 00:00:00'),
 Timestamp('2027-02-19 00:00:00'),
 Timestamp('2027-02-19 00:00:00'),
 Timestamp('2027-05-03 00:00:00'),
 Timestamp('2027-05-03 00:00:00'),
 Timestamp('2027-05-03 00:00:00'),
 Timestamp('2027-03-22 00:00:00'),
 Timestamp('2027-08-02 00:00:00'),
 Timestamp('2027-01-19 00:00:00'),
 Timestamp('2027-01-19 00:00:00'),
 Timestamp('2027-01-19 00:00:00'),
 Timestamp('2027-01-17 00:00:00'),
 Timestamp('2027-04-02 00:00:00'),
 Timestamp('2027-02-02 00:00:00'),
 Timestamp('2027-02-02 00:00:00'),
 Timestamp('2027-03-03 00:00:00'),
 Timestamp('2027-03-03 00:00:00'),
 Timestamp('2027-03-03 00:00:00'),
 Timestamp('2027-03-03 00:00:00'),
 Timestamp('2027-01-19 00:00:00'),
 Timestamp('2027-01-19 00:00:00'),
 Timestamp('2027-02-28 00:00:00'),
 Timestamp('2027-03-02 00:00:00'),
 Timestamp('2027-03-02 00:00:00'),
 Timestamp('2027-03-02 00:00:00'),
 Timestamp('2027-03-02 00:00:00'),
 Timestamp('2027-03-02 00:00:00'),
 Timestamp('2027-03-02 00:00:00'),
 Timestamp('2027-01-29 00:00:00'),
 Timestamp('2027-01-29 00:00:00'),
 Timestamp('2027-01-29 00:00:00'),
 Timestamp('2027-02-03 11:01:00'),
 Timestamp('2027-03-24 00:00:00'),
 Timestamp('2027-11-02 00:00:00'),
 Timestamp('2027-07-02 00:00:00'),
 Timestamp('2027-02-02 00:00:00'),
 Timestamp('2027-02-02 00:00:00'),
 Timestamp('2027-02-15 00:00:00'),
 Timestamp('2027-02-15 00:00:00'),
 Timestamp('2027-02-13 00:00:00'),
 Timestamp('2027-02-13 00:00:00'),
 Timestamp('2027-02-13 00:00:00'),
 Timestamp('2027-01-25 00:00:00'),
 Timestamp('2027-07-02 00:00:00'),
 Timestamp('2027-01-28 00:00:00'),
 Timestamp('2027-01-28 00:00:00'),
 Timestamp('2027-01-03 00:00:00'),
 Timestamp('2027-01-03 00:00:00'),
 Timestamp('2027-02-13 11:36:00'),
 Timestamp('2027-02-13 11:36:00'),
 Timestamp('2027-02-13 11:36:00'),
 Timestamp('2027-02-25 00:00:00'),
 Timestamp('2027-02-25 00:00:00'),
 Timestamp('2027-01-18 00:00:00'),
 Timestamp('2027-01-18 00:00:00'),
 Timestamp('2027-01-18 00:00:00'),
 Timestamp('2027-08-03 00:00:00'),
 Timestamp('2027-01-31 00:00:00'),
 Timestamp('2027-02-18 12:09:00'),
 Timestamp('2027-02-18 12:09:00'),
 Timestamp('2027-01-26 00:00:00'),
 Timestamp('2027-03-19 00:00:00'),
 Timestamp('2027-03-19 00:00:00'),
 Timestamp('2027-03-19 00:00:00'),
 Timestamp('2027-03-19 00:00:00'),
 Timestamp('2027-10-02 00:00:00'),
 Timestamp('2027-10-02 00:00:00'),
 Timestamp('2027-01-29 00:00:00'),
 Timestamp('2027-01-29 00:00:00'),
 Timestamp('2027-01-21 00:00:00'),
 Timestamp('2027-02-23 00:00:00'),
 Timestamp('2027-08-03 00:00:00'),
 Timestamp('2027-02-27 00:00:00'),
 Timestamp('2027-02-27 00:00:00'),
 Timestamp('2027-03-16 00:00:00'),
 Timestamp('2027-03-16 00:00:00'),
 Timestamp('2027-05-02 00:00:00'),
 Timestamp('2027-05-02 00:00:00'),
 Timestamp('2027-01-31 00:00:00'),
 Timestamp('2027-01-31 00:00:00'),
 Timestamp('2027-02-13 00:00:00'),
 Timestamp('2027-01-31 00:00:00'),
 Timestamp('2027-01-31 00:00:00'),
 Timestamp('2027-01-31 00:00:00'),
 Timestamp('2027-02-16 00:00:00'),
 Timestamp('2027-02-16 00:00:00'),
 Timestamp('2027-02-16 00:00:00'),
 Timestamp('2027-02-16 00:00:00'),
 Timestamp('2027-08-01 00:00:00'),
 Timestamp('2027-08-01 00:00:00'),
 Timestamp('2027-08-01 00:00:00'),
 Timestamp('2027-01-21 00:00:00'),
 Timestamp('2027-01-21 00:00:00'),
 Timestamp('2027-06-03 00:00:00'),
 Timestamp('2027-06-03 00:00:00'),
 Timestamp('2027-06-03 00:00:00'),
 Timestamp('2027-06-03 00:00:00'),
 Timestamp('2027-12-03 00:00:00'),
 Timestamp('2027-12-03 00:00:00'),
 Timestamp('2027-12-03 00:00:00')]

In [13]:
df["invoice_date"].tolist()

[Timestamp('2027-02-17 00:00:00'),
 Timestamp('2027-02-01 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-03-28 00:00:00'),
 Timestamp('2027-03-25 00:00:00'),
 Timestamp('2027-02-25 00:00:00'),
 Timestamp('2027-02-25 00:00:00'),
 Timestamp('2027-03-16 00:00:00'),
 Timestamp('2027-03-16 00:00:00'),
 Timestamp('2027-03-10 00:00:00'),
 Timestamp('2027-03-10 00:00:00'),
 Timestamp('2027-03-10 00:00:00'),
 Timestamp('2027-03-30 00:00:00'),
 Timestamp('2027-02-17 00:00:00'),
 Timestamp('2027-02-03 00:00:00'),
 Timestamp('2027-02-03 00:00:00'),
 Timestamp('2027-02-03 00:00:00'),
 NaT,
 NaT,
 Timestamp('2027-02-07 00:00:00'),
 Timestamp('2027-02-07 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-02-11 00:00:00'),
 Timestamp('2027-02-11 00:00:00'),
 Timestamp('2027-03-05 00:00:00'),
 Timestamp('2027-02-21 00:00:00'),
 Timestamp('2027-02-21 00:00:00'),
 Timestamp('2027-02-21 00:00:00'),
 Timestamp('2027-02-21 00:00:00'),
 Timestamp('2027-02-21 00:00:00'),
 Timestamp('2027-02-21 00:00:00'),
 Timestamp('2027-02-14 00:00:00'),
 Timestamp('2027-02-14 00:00:00'),
 Timestamp('2027-02-14 00:00:00'),
 Timestamp('2027-03-16 00:00:00'),
 Timestamp('2027-03-30 00:00:00'),
 Timestamp('2027-02-16 00:00:00'),
 NaT,
 Timestamp('2027-02-08 00:00:00'),
 Timestamp('2027-02-08 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-03-09 00:00:00'),
 Timestamp('2027-02-18 00:00:00'),
 Timestamp('2027-02-18 00:00:00'),
 Timestamp('2027-02-18 00:00:00'),
 Timestamp('2027-02-04 00:00:00'),
 NaT,
 Timestamp('2027-02-07 00:00:00'),
 Timestamp('2027-02-07 00:00:00'),
 Timestamp('2027-03-20 00:00:00'),
 Timestamp('2027-03-20 00:00:00'),
 Timestamp('2027-02-18 00:00:00'),
 Timestamp('2027-02-18 00:00:00'),
 Timestamp('2027-02-18 00:00:00'),
 Timestamp('2027-03-05 00:00:00'),
 Timestamp('2027-03-05 00:00:00'),
 Timestamp('2027-02-07 00:00:00'),
 Timestamp('2027-02-07 00:00:00'),
 Timestamp('2027-02-07 00:00:00'),
 Timestamp('2027-03-17 00:00:00'),
 Timestamp('2027-02-14 00:00:00'),
 Timestamp('2027-03-18 00:00:00'),
 Timestamp('2027-03-18 00:00:00'),
 Timestamp('2027-02-03 00:00:00'),
 Timestamp('2027-03-29 00:00:00'),
 Timestamp('2027-03-29 00:00:00'),
 Timestamp('2027-03-29 00:00:00'),
 Timestamp('2027-03-29 00:00:00'),
 Timestamp('2027-02-17 00:00:00'),
 Timestamp('2027-02-17 00:00:00'),
 Timestamp('2027-02-06 00:00:00'),
 Timestamp('2027-02-06 00:00:00'),
 Timestamp('2027-02-03 00:00:00'),
 Timestamp('2027-03-22 00:00:00'),
 Timestamp('2027-03-13 00:00:00'),
 Timestamp('2027-03-06 00:00:00'),
 Timestamp('2027-03-06 00:00:00'),
 Timestamp('2027-03-26 00:00:00'),
 Timestamp('2027-03-26 00:00:00'),
 Timestamp('2027-02-24 00:00:00'),
 Timestamp('2027-02-24 00:00:00'),
 Timestamp('2027-02-08 00:00:00'),
 Timestamp('2027-02-08 00:00:00'),
 Timestamp('2027-02-22 00:00:00'),
 Timestamp('2027-02-15 00:00:00'),
 Timestamp('2027-02-15 00:00:00'),
 Timestamp('2027-02-15 00:00:00'),
 NaT,
 Timestamp('2027-03-10 00:00:00'),
 Timestamp('2027-03-10 00:00:00'),
 Timestamp('2027-03-10 00:00:00'),
 Timestamp('2027-02-06 00:00:00'),
 Timestamp('2027-02-06 00:00:00'),
 Timestamp('2027-02-06 00:00:00'),
 Timestamp('2027-02-10 00:00:00'),
 Timestamp('2027-02-10 00:00:00'),
 Timestamp('2027-03-24 00:00:00'),
 Timestamp('2027-03-24 00:00:00'),
 Timestamp('2027-03-24 00:00:00'),
 Timestamp('2027-03-24 00:00:00'),
 Timestamp('2027-03-17 00:00:00'),
 Timestamp('2027-03-17 00:00:00'),
 Timestamp('2027-03-17 00:00:00')]

In [14]:

df["days_diff"] = (df["invoice_date"] - df["delivery_confirm_date"]).dt.days

In [19]:
df[df["days_diff"] < 0][["order_id", "invoice_date", "delivery_confirm_date", "days_diff"]]

            order_id invoice_date delivery_confirm_date  days_diff
0    ORD-2027-296460   2027-02-17            2027-10-02     -227.0
11   ORD-2027-116776   2027-03-10            2027-05-03      -54.0
12   ORD-2027-116776   2027-03-10            2027-05-03      -54.0
13   ORD-2027-116776   2027-03-10            2027-05-03      -54.0
15   ORD-2027-346967   2027-02-17            2027-08-02     -166.0
30   ORD-2027-340184   2027-02-21            2027-03-02       -9.0
31   ORD-2027-340184   2027-02-21            2027-03-02       -9.0
32   ORD-2027-340184   2027-02-21            2027-03-02       -9.0
33   ORD-2027-340184   2027-02-21            2027-03-02       -9.0
34   ORD-2027-340184   2027-02-21            2027-03-02       -9.0
35   ORD-2027-340184   2027-02-21            2027-03-02       -9.0
41   ORD-2027-911031   2027-02-16            2027-11-02     -259.0
64   ORD-2027-599775   2027-03-17            2027-08-03     -139.0
73   ORD-2027-966069   2027-02-17            2027-10-02     -227.0
74   ORD-2027-966069   2027-02-17            2027-10-02     -227.0
79   ORD-2027-610481   2027-03-13            2027-08-03     -143.0
84   ORD-2026-339139   2027-02-24            2027-05-02      -67.0
85   ORD-2026-339139   2027-02-24            2027-05-02      -67.0
96   ORD-2026-483219   2027-02-06            2027-08-01     -176.0
97   ORD-2026-483219   2027-02-06            2027-08-01     -176.0
98   ORD-2026-483219   2027-02-06            2027-08-01     -176.0
101  ORD-2027-881543   2027-03-24            2027-06-03      -71.0
102  ORD-2027-881543   2027-03-24            2027-06-03      -71.0
103  ORD-2027-881543   2027-03-24            2027-06-03      -71.0
104  ORD-2027-881543   2027-03-24            2027-06-03      -71.0
105  ORD-2027-126344   2027-03-17            2027-12-03     -261.0
106  ORD-2027-126344   2027-03-17            2027-12-03     -261.0
107  ORD-2027-126344   2027-03-17            2027-12-03     -261.0

In [16]:
df["days_diff"].tolist()

[-227.0,
 19.0,
 6.0,
 6.0,
 6.0,
 8.0,
 6.0,
 6.0,
 6.0,
 25.0,
 25.0,
 -54.0,
 -54.0,
 -54.0,
 8.0,
 -166.0,
 15.0,
 15.0,
 15.0,
 nan,
 nan,
 5.0,
 5.0,
 6.0,
 6.0,
 6.0,
 6.0,
 23.0,
 23.0,
 5.0,
 -9.0,
 -9.0,
 -9.0,
 -9.0,
 -9.0,
 -9.0,
 16.0,
 16.0,
 16.0,
 40.0,
 6.0,
 -259.0,
 nan,
 6.0,
 6.0,
 22.0,
 22.0,
 5.0,
 5.0,
 5.0,
 10.0,
 nan,
 10.0,
 10.0,
 76.0,
 76.0,
 4.0,
 4.0,
 4.0,
 8.0,
 8.0,
 20.0,
 20.0,
 20.0,
 -139.0,
 14.0,
 27.0,
 27.0,
 8.0,
 10.0,
 10.0,
 10.0,
 10.0,
 -227.0,
 -227.0,
 8.0,
 8.0,
 13.0,
 27.0,
 -143.0,
 7.0,
 7.0,
 10.0,
 10.0,
 -67.0,
 -67.0,
 8.0,
 8.0,
 9.0,
 15.0,
 15.0,
 15.0,
 nan,
 22.0,
 22.0,
 22.0,
 -176.0,
 -176.0,
 -176.0,
 20.0,
 20.0,
 -71.0,
 -71.0,
 -71.0,
 -71.0,
 -261.0,
 -261.0,
 -261.0]

In [20]:
# Here are we "Grouping By: count()" as we know from SQL, it counts the invoices that where send late and the ones that where on time
df["vida_10_day_rule"] = df["days_diff"].apply(
    lambda x: "Compliant" if x <= 10 else "Late"
)

In [21]:
#Just showing the results
df["vida_10_day_rule"].value_counts()

vida_10_day_rule
Compliant    71
Late         32
Name: count, dtype: int64