# Lecture 1 - Python Basics

## 🧑‍💻 Hands-on 

You will be given this course material after the lecture. So you can save as your own copy to re-read, practice and write your notes. 

To run the examples or experiement new ones, I recommend you to:

1. Open **Python Native REPL** editor. (Remember how to bring it up?)
2. Run and modify examples to see output instantly.

## Exercise & Reference

The accompanying exercise is `W13 Exercise - Execution and State Tracing.md` and its answer sheet. 

If you have Markdown All in One extension installed, right-click and print them to `.html` if this help you to read them. It takes a while to get used to Markdown and Jupyter Notebook - no worries. 

It is designed to start a mindset shift torwards Python. It might be good if you could:
- Have a pen and a piece of paper to start with
- Start with LEVEL 1: Beginner. 
- Follow the way the worksheet is designed. Take it step-by-step.
- It is really NOT a problem if you find some quite difficult and cannot complete them just yet. We will repeat these concepts quite a few times in the next few weeks.
- Take your time and learn the foundation. 
- Afterwards, type the code into Python Native REPL and see what it return.

Two additional references for you to read if you are interested:

- `W13 Reference - Python for Beginners.md` is a handy doc to help you to get started. You can of course make a personal copy and add your own notes to it - as your own cheat sheet.
- `W13 Reference - Regex a Guide for Beginners.ipynb` is good for looking up information when needed.

## Python Basics - Orientation

Python Basics is not a small subject. Let'stake an orientation tour to get us started. All concpets come with examples you can test in the Python REPL editor. Most have a reference to W3School or Real Python so you can read about them. 

It is not a problem that you find some concepts a bit confusing, we will work more on some of them in the upcoming lectures. This is just the first step for you to get familiar with the language grammar.

### 1. Language Characteristics

Python is an **interpreted, high-level, general-purpose** programming language. Its core features include:

- **Dynamic Typing**: Variable types are determined at runtime based on the assigned value — no need to declare a type in advance. This improves development flexibility.
- **Interpreted Language**: Code is interpreted and executed line-by-line at runtime, skipping a compilation step and speeding up the development-test cycle.

### 2. Data Types

Read about data types at [W3schools.com](https://www.w3schools.com/python/python_datatypes.asp)

Basic types:

| Type | Example | Notes |
|------|---------|-------|
| `int` | `42` | Whole numbers |
| `float` | `3.14` | Decimal numbers |
| `str` | `"hello"` | Text, single or double quotes |
| `bool` | `True`, `False` | Always capitalised |
| `NoneType` | `None` | Absence of a value (see section 11) |

Essential built-in types we'll covered in depth in Lecture 2:

| Type | Example | Mutable? |Brackets|
|------|---------|----------|----------|
| `list` | `[1, 2, 3]` | Yes | Square brackets|
| `tuple` | `(1, 2, 3)` | No | Parenthese or round brackets |
| `dict` | `{"fruit": "apple","type": "granny smith"}` | Yes | Braces or curly brackets, key value pair |
| `set` | `{1, 2, 3}` | Yes | Braces or curly brackets |

In [ ]:
name = "Alice"          # str
age = 30                # int
score = 98.5            # float
is_active = True        # bool

# Check the type of any value
print(type(name))
print(type(age))

<class 'str'>
<class 'int'>

### 3. Variables

Variables are created via assignment. There is no need to declare a type first.

Variables are assigned via `=`. The Python equal sign is `==`. See more about operators in section 9 below. 

Variables must be defined (assigned a value) before use, otherwise a `NameError` will occur.

Read more on [W3Schools](https://www.w3schools.com/python/python_variables.asp).

In [ ]:
var1 = 1
var2 = 10

# Assign the same value to multiple variables
a = b = c = 1

# Assign multiple values at once (unpacking)
a, b, c = 1, 2, "Python"
print(a, b, c)

1 2 Python

### 4. Strings & f-strings

Strings can use single or double quotes. 

For formatting values into strings, use **f-strings** (Python 3.6+): prefix the string with `f` and place any expression inside `{}`. It is an easy way to generate strings that contain interpolated expressions. Any code between curly braces {} will be evaluated and then the result will be turned into a string and intserted into the overall string. 

F-strings are really useful. Try with below examples. Read more at [W3schools.com](https://www.w3schools.com/python/python_string_formatting.asp)

In [ ]:
product = "Headset"
revenue = 7576.725
growth = 0.0523

# Basic embedding
print(f"Product: {product}")            # Product: Headset

# Number formatting
print(f"Revenue: {revenue:,.2f}")       # Revenue: 7,576.73
print(f"Growth:  {growth:.1%}")         # Growth:  5.2%

# Any expression works inside {}
print(f"Double revenue: {revenue * 2:,.0f}")    # Double revenue: 15,153

Product: Headset
Revenue: 7,576.73
Growth:  5.2%
Double revenue: 15,153

### 5. Operators

Python supports the following categories of operators:

| Category | Examples |
|---|---|
| Arithmetic | `+`, `-`, `*`, `/`, `//`, `%`, `**` |
| Comparison | `==`, `!=`, `>`, `<`, `>=`, `<=` |
| Logical | `and`, `or`, `not` |
| Assignment | `=`, `+=`, `-=`, `*=`, `/=` |
| Membership | `in`, `not in` |
| Identity | `is`, `is not` |

Note: `/` always returns a float; `//` is floor (integer) division.

Read more on [W3Schools](https://www.w3schools.com/python/python_operators.asp).

In [ ]:
print(10 + 3)   # 13 — addition
print(10 - 3)   # 7  — subtraction
print(10 * 3)   # 30 — multiplication
print(10 / 3)   # 3.333... — division
print(10 // 3)  # 3  — floor division
print(10 % 3)   # 1  — modulo
print(10 ** 3)  # 1000 — exponentiation

13
7
30
3.3333333333333335
3
1
1000

### 6. Conditional Statements & Control Flow

Python by default evaluates every line of code from top to bottom, sequentially. The order in which Python runs our code is called **control flow**, and Python provides functionality we can use to change the control flow. 

The first tool Python provides for us is the **if-statement**. 

We write an [**if-statement**](https://www.w3schools.com/python/gloss_python_if_statement.asp) like this:

```python
    if bool:
        code_1
    else:
        code_2
```

`bool` here is a boolean expression, evaluating to either **`True`** or **`False`**

Think of this as a fork in the road. Python will read the boolean at the top, then if it is **`True`**, it will execute **`code_1`** not **`code_2`**

If it is **`False`**, it will skip **`code_1`** and only execute **`code_2`**

Read more about control flow on [Real Python](https://realpython.com/python-control-flow/).

In [ ]:
age = 19

if age >= 20:
    print("Come on in")
else:
    print("Go home kid")

Go home kid

For multiple conditions, one can use `if-elif-else`.

```python
    if condition_1:
        code_1
    elif condition_2:
        code_2
    else:
        code_3
```

In [ ]:
score = 85

if score >= 90:         
    grade = 'A'
elif score >= 80:
    grade = 'B'
else:
    grade = 'C'

print(f"Score: {score} → Grade: {grade}") #

Score: 85 → Grade: B

### 7. Loops

- **`for` loop**: iterates over an iterable (list, string, `range()`, etc.).

```python
for item in iterable:
    statement
```

- **`while` loop**: repeats while a condition is `True`. 

```python
while expression:
    statement
```

Read more on [W3Schools](https://www.w3schools.com/python/python_for_loops.asp).

In [ ]:
# for loop over a range
for i in range(4):       # 0, 1, 2, 3
    print(i, end=" ")
print()

# for loop over a list
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# enumerate() — index + value together
for i, fruit in enumerate(fruits, start=1):
    print(f"{i}. {fruit}")

# while loop
count = 5
while count > 0:        # as long as count is larger than 0
    count -= 1          # reduce 1
    print(count)

0 1 2 3
apple
banana
cherry
1. apple
2. banana
3. cherry
4
3
2
1
0

### 8. Functions

Functions are defined with `def`. They can have default argument values, return multiple values (as a tuple), and include a docstring explaining their purpose.

**Scope:** variables created inside a function are **local** — they only exist within that function and are gone when it returns.

Read more on [W3Schools](https://www.w3schools.com/python/python_functions.asp).

In [ ]:
def greet(name, greeting="Hello"):
    """Return a greeting string. 'greeting' has a default value."""
    return f"{greeting}, {name}!"

print(greet("Alice"))                # uses default
print(greet("Bob", greeting="Hi"))   # override default

# Returning multiple values
def min_max(values):
    return min(values), max(values)

lo, hi = min_max([3, 1, 4, 1, 5, 9])
print(f"Min: {lo}, Max: {hi}")

# Lambda — a compact anonymous function
double = lambda x: x * 2
print(double(7))   # 14

Hello, Alice!
Hi, Bob!
Min: 1, Max: 9
14

### 9. Methods

A **method** is a function that belongs to an object. Where a standalone function is called as `function(object)`, a method is called *on* the object using dot notation: `object.method()`. Methods automatically have access to the object they are called on.

Every data type in Python comes with its own set of built-in methods, such as:

- str.upper()
- str.split()
- list.append()
- list.sort()
- dict.keys()

Below are a few examples. 

The key distinction:
- `len(my_list)` — built-in **function**, takes the object as an argument
- `my_list.append(4)` — **method**, called on the object itself

You will encounter this pattern constantly in Lecture 2 (`str.upper()`,`str.split()`,`list.append()`, `list.sort()`) and later throughout pandas (`df.head()`, `df.groupby()`, `series.mean()`, etc.).

Read more on [W3Schools](https://www.w3schools.com/python/python_lists_methods.asp).

In [ ]:
# String methods
text = "  hello, world  "
print(text.strip())           # remove whitespace: 'hello, world'
print(text.upper())           # 'HELLO, WORLD'
print(text.replace(",", ";")) # 'hello; world'

# List methods
numbers = [3, 1, 4, 1, 5]
numbers.append(9)             # modifies the list in place
numbers.sort()                # modifies the list in place
print(numbers)

hello, world
  HELLO, WORLD
  hello; world
[1, 1, 3, 4, 5, 9]

### 10. Comments

- **Single-line comment**: starts with `#`, extends to end of line.
- **Multi-line comment**: use triple quotes `'''` or `"""`. Technically these are multi-line strings, often used as docstrings or block comments.

In [ ]:
'''
This is a multi-line comment, often used as a module or function docstring
to describe its purpose and usage.
'''

is_authenticated = True
has_permissions = True

if is_authenticated:
    # This block belongs to the if statement
    print("Authentication successful.")
    if has_permissions:
        # This is a nested if block
        print("Access granted.")

Authentication successful.
Access granted.

### 11. Indentation & Code Blocks

Python uses indentation to show **code hierarchy** — and it's not just formatting, it's logic and a clear visual structure. All statements in the same code block must use the same indentation level — the standard is **4 spaces**.

Here is an example:

```python
if score > 50:
    print("Pass")       # only runs if score > 50
    if score > 90:
        print("Distinction")  # only runs if score > 90
print("Done")           # always runs
```

- Each indentation level = one more layer of nesting
- Reading tip: follow the indentation to understand *what controls what*

In [ ]:
# Correct indentation
if True:
    print("True")
else:
    print("False")

# ❌ Inconsistent indentation causes an IndentationError:
# if True:
#     print("Answer")
#     print("True")
# else:
#     print("Answer")
#   print("False")    # Wrong indentation — runtime error

True

### A Note on ...

#### Identifiers

Identifiers are names used to label variables, functions, classes, and other entities. The naming rules are:

- Composed of letters (`A-Z`, `a-z`), digits (`0-9`), and underscores (`_`).
- The first character **cannot** be a digit.
- **Case-sensitive**: `oneVariable` and `OneVariable` are different identifiers.
- Python reserved keywords **cannot** be used as identifiers. See next section.

Read more on [Real Python](https://realpython.com/ref/glossary/identifier/).

#### Reserved Keywords

Reserved words (keywords) cannot be used as identifiers. You can view them all with below code.

Read more about Python keywords on [Real Python](https://realpython.com/python-keywords/).

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

In [ ]:
# To see list in easier to read format

from pprint import pprint
pprint(keyword.kwlist)

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

####  `None` & `NoneType`

`None` represents the **absence of a value**. It is its own type (`NoneType`) and is Python's equivalent of a null. A few important rules:

- Always check for `None` using `is None`, not `== None`
- `None` is not `0`, not `False`, not an empty string — it is uniquely itself
- A function that reaches its end without a `return` statement implicitly returns `None`

Read more on [W3Schools](https://www.w3schools.com/python/python_none.asp).

In [ ]:
result = None

print(result is None)     # True  — correct way to check
print(result == False)    # False — None is not False
print(result == 0)        # False — None is not zero
print(type(result))       # <class 'NoneType'>

True
False
False
<class 'NoneType'>

### Python Official Doc

| Topic | Link |
|-------|------|
| Official Python tutorial | https://docs.python.org/3/tutorial/ |
| Lexical analysis (syntax rules) | https://docs.python.org/3/reference/lexical_analysis.html |
| Built-in types | https://docs.python.org/3/library/stdtypes.html |
| f-strings (PEP 498) | https://peps.python.org/pep-0498/ |
| Control flow | https://docs.python.org/3/tutorial/controlflow.html |
| Methods (classes & instances) | https://docs.python.org/3/tutorial/classes.html#instance-objects |
| Errors and exceptions | https://docs.python.org/3/tutorial/errors.html |
| Modules | https://docs.python.org/3/tutorial/modules.html |
| None / NoneType | https://realpython.com/null-in-python/ |

## BREAK TIME 🐍

>Why do Python programmers prefer dark mode?<br>
>*Because light attracts bugs!*

## Programming Concepts - in Plain English

At start, some of us who are new to Python could use some help to shift towards a Pythonic mindset. Here we'll use a language analogy and see a few essential Python concepts in **roles**, just like parts of speech in a language:

| Programming Concept | Plain English Equivalent | Role | 
|---|---|---|
| **Variable** | A named container for data | Noun |
| **Function** | An action performed on data | Verb | 
| **Conditional** | A decision or branch | If-then sentence |
| **Loop** | Doing something multiple times | Repetition |

Once you read code through this lens, complexity drops.

### The Four Building Blocks

#### 1. Variables — Labeled Boxes

A variable is simply a **labeled box**. The label is the name; the box holds data.

**Key insight**: **`=` is not mathematical equality.** It means *"put the right side into the box on the left."*

- `a = 5` → put 5 into box `a`
- `a = a + 1` → take what's in box `a`, add 1, put it back

Run below code blocks. Follow changes made to variables in Terminal > JUPYTER VARIABLE.

In [ ]:
name = "Alice"   # box labeled "name", contains the string "Alice"
age = 18         # box labeled "age", contains the number 18
height = 1.65      # box labeled "height", contains the decimal 1.65

In [ ]:
# What to list all variables in-memory? Use

%whos

Traceback (most recent call last):
  File "c:\Users\CeciliaBack\.vscode\extensions\ms-python.python-2026.4.0-win32-x64\python_files\python_server.py", line 139, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 3
    %whos
    ^
SyntaxError: invalid syntax

##### A Note on Deleting Variables

If you are working in Notebook to, for example, simulate a data cleansing in pipeline design. You want to use temporary tables (dataframes as variables, we will learn these later) during transformation and then delete the temporary tables when you have a cleaned dataset. 

You may need to delete one or several variables. Below will be useful.

In [ ]:
# Alternatively, one can select a variable to delete.

del height, age

`%reset` and `%reset_selective`can remove multiple variables without naming each one of them. However, it's good to first understand how they behave in Jupyter Notebook in VSCode before using them in your future projects.

In [ ]:
%reset_selective -f na*

Traceback (most recent call last):
  File "c:\Users\CeciliaBack\.vscode\extensions\ms-python.python-2026.4.0-win32-x64\python_files\python_server.py", line 139, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1
    %reset_selective -f na*
    ^
SyntaxError: invalid syntax

In [ ]:
# Now let's clear the variables without restart kernel. You will be prompt to confirm. See the menu window.

%reset

Traceback (most recent call last):
  File "c:\Users\CeciliaBack\.vscode\extensions\ms-python.python-2026.4.0-win32-x64\python_files\python_server.py", line 139, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 3
    %reset
    ^
SyntaxError: invalid syntax

#### 2. Functions — Named Actions

A function is a **reusable action**. It takes data, does something, and often returns a result.

Run below code blocks.

In [ ]:
print("hello")  # action: display something

hello

In [ ]:
len("hello")    # action: calculate length → returns 5

help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

In [ ]:
# Pay attention to the popup at the top menu window to enter input

input("Your name: ") # action: wait for user to type something

#### 3. Conditionals — Decisions

`if` is just **"if… then…"** in structured form.

Reading tip: ignore the syntax first, read the logic — *"if age is greater than 18, print adult, otherwise print minor."*

In [ ]:
# age = 27

if age > 18:
    print("You're an adult")
else:
    print("You're a minor")

Traceback (most recent call last):
  File "c:\Users\CeciliaBack\.vscode\extensions\ms-python.python-2026.4.0-win32-x64\python_files\python_server.py", line 139, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 3, in <module>
NameError: name 'age' is not defined

#### 4. Loops — Repetition

A loop means **"repeat this action."** Nothing more.

- `for` loops repeat a set number of times
- `while` loops repeat until a condition becomes false

When reading or building a loop, ask yourself: *"what is being repeated, and when does it stop?"*

We will work more on these as part of Control Flow lecture next week.

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4

In [ ]:
i = 5

while i < 10:
    print(i)
    i +=1

5
6
7
8
9

### Execution Order and State

Above we looked at programming concepts with a language analogy, I hope that's helpful. 

However, in code, things don't remain static. Rather, they *change*. We are now looking at Execution Order and State.

Let's use a few examples to look, slowly and closely, at how *data* change while the code runs.

**Execution order** means code runs line by line, top to bottom (unless a loop or function call redirects it). The sequence matters:

```python
x = 5
x = x + 1
print(x)   # prints 6, not 5
```

**State** is the current value of all variables at any given moment during execution. As the program runs, state changes constantly.

```python
score = 0          # state: score is 0
score = score + 10 # state: score is now 10
score = score + 5  # state: score is now 15
print(score)       # prints 15
```

#### Why This Matters

- Reading code as static text will mislead you
- You need to **mentally trace execution** — imagine running the code step by step in your head
- Ask yourself at each line: *"What are the current values of my variables right now?"*

#### A Practical Technique: The State Table

When reading unfamiliar code, track state manually:

```python
a = 2
b = 3
a = a + b
b = a - b
a = a - b
```

| Line | a | b |
|---|---|---|
| `a = 2` | 2 | — |
| `b = 3` | 2 | 3 |
| `a = a + b` | 5 | 3 |
| `b = a - b` | 5 | 2 |
| `a = a - b` | 3 | 2 |

This is how experienced programmers debug code mentally. It's a skill, and it's learnable.

If you find the above State Table exercise useful, there is an exercise notebook named **Execution and State Tracing**. Work on it alongside this week's lectures. It may help to practice.

### A Few More Words On Reading Code

Above we have gone through some basic concepts and building blocks with simple code examples. 

Next we will have a look at a few tips to read Python code clearly. This helps us to develop good habit and learn to write, hopefully, well-structured clean code in the nearest future. 

#### Read Code Structurally

Don't start with details. Read in layers:

1. **Scan the structure** — where are the functions, loops, and conditionals?
2. **Follow the data flow** — what goes in, what comes out, what changes?
3. **Trace execution order** — what runs first? What triggers what?
4. **Read the details** — now zoom into individual lines

Think of it like reading a building blueprint:
- First: how many floors, where are the walls?
- Then: where do the pipes run?
- Finally: what are the light fittings?

#### A Path to Fluency

Learning to read code is like learning a language — with one key difference:

**Language fluency:** exposure + pattern recognition  
**Code fluency:** exposure + pattern recognition + **active execution tracing**

Progress looks like this:

- *Stage 1:* Can't understand individual lines
- *Stage 2:* Understand individual lines, but not the whole
- *Stage 3:* Understand blocks and structure
- *Stage 4:* Can predict what comes next
- *Stage 5:* Can spot bugs before running the code

The gap between Stage 2 and Stage 3 is usually structural reading. The gap between Stage 3 and Stage 4 is execution tracing.

### Practice the Four Building Blocks

These four things cover 80% of beginner code:

- **Variables** — how data is stored and named
- **Functions** — how actions are defined and called
- **Conditionals** — how decisions are made
- **Loops** — how repetition is controlled

Master these, plus the habit of **tracing execution and tracking state**, and you can read most entry-level project code.

Frameworks, classes, decorators, modules — those are later layers. Learn to read everyday conversation before tackling literature.

## END OF LECTURE 🐍

> Why was the Python developer calm during the crisis? <br>
> *Because they knew how to handle exceptions.*

## Keyboard Shortcut: Jupyter in VSCode

Below works if you haven't yet customized  keyboard shortcut on your VSCode.

Mac users can replace `Ctrl` with `Cmd`.

- ESC : Change the cell mode
- Enter: Edit cell
- A : Add a cell above
- B : Add a cell below
- M : switch the cell type to Markdown
- Y : switch the cell type to code
- J or down arrow key : Go to cell below
- K or up arrow key : Go to cell above
- Alt + down/up Arrow: Move cell up or down 
- Alt + left/right Arrow: Move to first/last block in notebook
- Ctrl + Enter : Run the currently selected cell
- Shift + Enter : Run the currently selected cell and insert a new cell immediately below (focus moves to new cell)
- Alt + Enter : Run the currently selected cell and insert a new cell immediately below (focus remains on current cell)
- dd : Delete a selected cell
- L : Enable/Disable line numbers
- Ctrl + S : Save

Based on [Medium - VSCode Jupyter Notebook Keyboard Shortcuts](https://bbyond.medium.com/vscode-jupyter-notebook-keyboard-shortcuts-31fab95fa301)

# Lecture 2 - Python Built-ins for Data Analysis

In lecture 1, we took a glance at some basic concepts in Python. It may seem daunting. Therefore, we then looked at a few of the building blocks in Python programming, in an analogy with language: variable (noun), function (action), conditionals (if else), loops (repetition). After that, I hope you have had time to re-read the material and try your hands on the examples in your Python Native REPL, which stands for Read-Eval(uate)-Print Loop. How did it go with Exercise - Execution and State Tacing? 

Today's lecture is titled **Code to Learn** - this is a reversed way to the usual phrase **Learn to Code**. We will get to why we reverse the order of the more common phrase. 

First, we will take a closer look at a few essential Python built-ins for Data Analysis: 

- Data types
- Comprehensions
- String & string method
- Some built-in functions

These are crucial concepts with frequently used patterns. Please work hands-on with the examples provided. Lecture 2 exercise will be published after the lecture. 

As you may have noticed, we already have seen Control Flow (loops & if-else) and Functions (simple ones) in lecture 1 and 2. In next week's lecture 3 and 4, we will not go super complicated with these. We will use what's in Basics and Built-ins to learn and practice Control Flow and Functions. So, keep working hands-on 🧑‍💻 with the course notes and exercise - you are doing great! 🙌

## Data Types

These four data types are also called collection data types or arrays.

### Tuple
An **ordered, immutable** sequence. Stored in round brackets as such `()`.

Use tuples for data that must not change — configuration values, coordinate pairs, fixed column schemas. Functions also return multiple values as tuples.

Read more on [W3Schools](https://www.w3schools.com/python/python_tuples.asp).

In [ ]:
# Tuple
dimensions = (1920, 1080)
x, y = dimensions               # unpacking
print(x, y)

# Try below, you will receive TypeError because tuples are immutable
# dimensions[0] = 800

### Lists

A list is an **ordered, mutable** sequence. It can hold any mix of types. Lists are **the most common data container** you will work with before loading data into a DataFrame.

List uses square brackets `[]` and it can be created empty as a placeholder.

Below we'll have a look at indexing & slicing using `[]` and `:` and some common list methods.

#### Indexing and Slicing

Python index starts from 0. You can read about list index() method at [DataCamp](https://www.datacamp.com/tutorial/python-list-index).

In [ ]:
scores = [88, 72, 95, 60, 84, 91]

# Indexing and slicing
print(scores[0])       # first element: 88
print(scores[-1])      # last element: 91
print(scores[1:4])     # slice: [72, 95, 60]
print(scores[:3])      # first 3: [88, 72, 95]
print(scores[::2])     # every 2nd: [88, 95, 84]

# show all scores
for s in scores:
    print(s)

# show scores indexes
for s in scores:
    print(scores.index(s))

# or use enumerate() to show indexes next to list
for i, score in enumerate(scores):
    print(i, score)

#### List Methods

> A **method** is a function that belongs to an object. Where a standalone function is called as `function(object)`, a method is called *on* the object using dot notation: `object.method()`. Methods automatically have access to the object they are called on.

When our object example is `scores`, the list method would look like `scores.method()`.

In [ ]:
# Modifying
scores.append(78)           # add to end
scores.insert(0, 100)       # insert at position. Here at index 0 (the first position)
scores.remove(60)           # remove first occurrence of value
popped = scores.pop()       # remove and return last element

# Useful list methods
print(len(scores))          # length
print(scores.count(88))     # how many times 88 appears
print(sorted(scores))       # returns a new sorted list
scores.sort(reverse=True)   # sorts in place
print(scores)

### Dictionaries

A dictionary stores **key-value pairs** (one pair or many pairs). Since Python 3.7 dictionaries preserve insertion order - that is *append at the end*. 

**Keys must be unique and immutable** (strings and numbers are the most common keys). In a certain sense, we can say *keys* are similar to *column names*.

In Pythonic-flavored data work, a *dict* often represents a single record —  that is one row of named fields. In such a sense, a *list* of *dict* is more comparable to a table that we are more familar with. 

A Dict is stored in curly braces as such `{}`.

Read more on [W3Schools](https://www.w3schools.com/python/python_dictionaries.asp).

In [ ]:
# an example of 1 dict

record = {
    "id": 108,
    "product": "Headset",
    "revenue": 5000,
    "in_store": True
}

# Access
print(record["product"])                  # KeyError if missing
print(record.get("margin", 0))            # returns 0 if missing

# Add / update
record["margin"] = 0.35
record["revenue"] = 5500                   # update existing key

# Remove
record.pop("in_store")                     # removes and returns the value

# Iterating — the three common patterns
for key in record:                        # iterate over keys
    print(key)

for value in record.values():             # iterate over values
    print(value)

for key, value in record.items():        # iterate over both
    print(f"{key}: {value}")

# Check if exists
print("revenue" in record)               # True
print("discount" in record)              # False

### Set

An **unordered collection of <font color=MediumOrchid>unique</font> elements**. Sets are optimised for membership testing and removing duplicates. This make it very handy in data analysis.

> So what type of brackets store a set?

That will be `{}`. Good to know that set() always returns a set object — it never preserves the original type, meaning if we apply set() on a list, the returned results will be a set, not a list. 

You can read more about **set** at [W3schools](https://www.w3schools.com/python/python_sets.asp).

In [ ]:
# Set
departments_raw = ["Sales", "HR", "Sales", "Finance", "HR", "HR"]
departments = set(departments_raw)          # duplicates removed
print(departments)                          # order is not guaranteed

# Fast membership test — O(1) regardless of set size
print("Sales" in departments)   # True

# Set operations — useful for comparing datasets
team_a = {"Alice", "Bob", "Carol"}
team_b = {"Bob", "Carol", "Dave"}

print(team_a & team_b)          # intersection: {'Bob', 'Carol'}
print(team_a | team_b)          # union: all members
print(team_a - team_b)          # difference: only in team_a

### Casting (specify type)

When you want to assign a type to a variable, use casting functions. Read more on [W3School](https://www.w3schools.com/python/python_casting.asp)

In [ ]:
type(int(2.8))
int("3")
float(1)
float("50000")

# practice an f-string
variable = "289"
print(f"{variable} is a {type(variable)} type & is now casted to {int(variable)} {type(int(variable))}")

## Comprehensions

Comprehensions are a concise, readable way to build new lists, dicts, or sets from existing data — with optional filtering. They replace many simple `for` loops in idiomatic Python. This has a more Pythonic flavor.

> Remember the language analogy in lecture 1? <br>
> In a similar way we can say:<br>
> **comprehension** is a noun - it creates a new thing (a list, dict...)<br>
> **`for` loop** is like a verb to do something repetitively

**General form:**

```python
[expression for item in iterable if condition]
```
The `if condition` part is optional.

Comprehensions are very useful so it worths spending time reading and practicing them.  

Some **useful resources** here. The beginner ones get you started. The intermediate ones are for you to learn and look up gradually as you progress.

- Beginner: [Python - list comprehension on W3School](https://www.w3schools.com/python/python_lists_comprehension.asp)
- Intermediate: [Python - Add custom value key in list of dictionaries on Geeks for Geeks](https://www.geeksforgeeks.org/python/python-add-custom-values-key-in-list-of-dictionaries/)
- Intermediate: [Python dictionary comprehensions on Real Python](https://realpython.com/python-dictionary-comprehension/)
- Intermediate: [Python dictionary comprehension tutorial (with 39 code examples) on Dataquest](https://www.dataquest.io/blog/python-dictionary-comprehension-tutorial/)

Below are some common patterns we can use.

In [ ]:
# We have a list with a number of dicts as element

products = [
    {"name": "Widget A", "revenue": 50000, "category": "Hardware"},
    {"name": "Widget B", "revenue": 12000, "category": "Software"},
    {"name": "Widget C", "revenue": 95000, "category": "Hardware"},
    {"name": "Widget D", "revenue": 3000,  "category": "Software"},
]

#### List Comprehension

In [ ]:
# All product names
names = [p["name"] for p in products]
print(names)

# Only high-revenue products
high_value = [p["name"] for p in products if p["revenue"] > 20_000]
print(high_value)

# Transform: apply a 10% uplift to all revenues
uplifted = [p["revenue"] * 1.1 for p in products]
print(uplifted)

#### Dict comprehension

In [ ]:
# Build a name → revenue lookup
revenue_map = {p["name"]: p["revenue"] for p in products}
print(revenue_map)

# Only Hardware products in the lookup
hardware_map = {p["name"]: p["revenue"] for p in products if p["category"] == "Hardware"}
print(hardware_map)

### Set Comprehension

In [ ]:
# Distinct categories
categories = {p["category"] for p in products}
print(categories)

## BREAK TIME 🐍

>How many programmers does it take to change a light bulb? <br>
>*None — that's a hardware problem.*

## String & String Method

Real-world data is full of messy strings. Python's string methods handle the most common cleaning tasks without any library.

If you want to read help in Python on string.method(), an easy way is use Python Native REPL to type `help(str` follwed by `.` so built-in string method list will show. 

You can also explore the list of string.methods by print them as list. Try below code and see what you find.

```python
for m in dir(str):
    if not m.startswith('_'):
        print(m)
```

Below are some examples applying string methods on a variable. Modify the variable and see if results are as you expecte them.

### Cleaning & format

In [ ]:
raw = "  Widget A — Revenue: 50,000 EUR  "

print(raw.strip())              # remove leading/trailing whitespace
print(raw.lower())
print(raw.upper())

### Search & replace

In [ ]:
# Search
print("Revenue" in raw)         # True
print(raw.startswith("  "))     # True
print(raw.find("Revenue"))      # index position of match

# Replacing
cleaned = raw.strip().replace(",", "").replace("EUR", "").strip()
print(cleaned)

### Split, join & parse

In [ ]:
# Splitting — turn a string into a list
csv_line = "North,88,Hardware,Active"
fields = csv_line.split(",")
print(fields)                   # ['North', '88', 'Hardware', 'Active']

# Joining — turn a list back into a string
print(" | ".join(fields))

# Parsing a number from text
amount_str = "50000"
amount = float(amount_str)
print(amount * 1.1)

### *Extras: String & Regex (Regular Expression)*

This is a more advanced topic.

It is common in data cleansing that we will need to work with regex patterns. Have a look at the following for extended reading on this topic:

- W13 Reference - Regex a Guide for Beginner.ipynb
- Official doc: [Python 3 Doc: Regular Expression HOWTO](https://docs.python.org/3/howto/regex.html)
- Regex online editor: [regex101](regex101.com)

## Some Built-in Functions for Data

These are always available — no import needed. Together they cover most of what you need for quick data summarisation and transformation.

Read about more [Python built-in functions at Python.org](https://docs.python.org/3/library/functions.html)

Below are some examples for you to try out.

### Numericals

In [ ]:
values = [3, 8, 1, 6, 4, 9, 2, 7, 5]

print(len(values))             # 9
print(sum(values))             # 45
print(min(values))             # 1
print(max(values))             # 9
print(round(sum(values) / len(values), 2))  # average: 5.0

### Sorting

In [ ]:
print(sorted(values))                      # new sorted list, ascending
print(sorted(values, reverse=True))        # descending

In [ ]:
# Sort a list of dicts by a field

records = [{"name": "C", "score": 85}, {"name": "A", "score": 92}, {"name": "B", "score": 78}]

by_score = sorted(records, key=lambda r: r["score"], reverse=True)
print(by_score)

### `format()`

Sometimes it's necessary to beautify for example number format. This function returns string type. Below are some examples with commonly used number format.

If we run `help(format)`, we will see:

```
format(value, format_spec='', /)
    Return type(value).__format__(value, format_spec)
```

If very interested in reading about `format_spec` mentioned above, one can read [Python doc: format specification mini language](https://docs.python.org/3/library/string.html#format-specification-mini-language).

For a hands-on practical guide, please refer to [DataCamp - Python f-string: A Complete Gudie](https://www.datacamp.com/tutorial/python-f-string).

In [ ]:
sales = 50000
units = 10

print(f"Sales: {sales:,}")                      # Sales: 50,000
print(f"Sales: {sales:,.2f}")                   # Sales: 50,000.00
print(f"Sales: {int(sales/units):>10,}")        # Sales:      5,000 shows right aligned result
print(f"Growth: {0.1374:.1%}")                  # Growth: 13.7%

In [ ]:
# Try below example and see results

reps = [("Alice", 15000), ("Bob", 8200), ("Carol", 23000)]

for name, sales in reps:
    print(f"{name:<10} SEK {sales:>10,.0f}")

### `enumerate()`

This function allows you to loop through an iterable (list, tuple, string) and have access to both the index and the element itself.

For further use of `enumerate()`, read on [Real Python](https://realpython.com/python-enumerate/).

In [2]:
# again, we can use enumerate() — index + value

regions  = ["North", "South", "East"]

for i, region in enumerate(regions, start=1):
    print(f"{i}. {region}")

1. North
2. South
3. East

### `any() / all()`

These pass logical tests across a collection. Examples below:

In [ ]:

scores = [88, 72, 95, 60, 84]
print(all(s >= 50 for s in scores))   # True — everyone passed
print(any(s >= 90 for s in scores))   # True — at least one distinction

## Further Reading

| Topic | Link |
|-------|------|
| Data structures (official tutorial) | https://docs.python.org/3/tutorial/datastructures.html |
| Built-in functions | https://docs.python.org/3/library/functions.html |
| String methods | https://docs.python.org/3/library/stdtypes.html#string-methods |
| List comprehensions | https://realpython.com/list-comprehension-python/ |
| Sorting (HOW-TO) | https://docs.python.org/3/howto/sorting.html |

## BREAK TIME 🐍

>What's a programmer's favorite hangout spot?<br>
>*The Foo Bar!*

# Lecture 3 - Control Flow

**Based on:** [Python for Data Analysis, Ch. 2 – Control Flow](https://wesmckinney.com/book/python-basics#control_flow) by Wes McKinney

> 📖 **Read alongside this notebook:** Open the link above in a browser tab and use it as parallel study material. Wes covers the same topics — these examples are here to make the concepts concrete.

---

We have seen and written control flow (if/else and loops) in our earlier lectures/exercises.

**Control flow** is how we make Python *decide* things and *repeat* things.  
Without it, a script just runs top to bottom, once — not very useful.

**Topics covered:**

1. `if / elif / else`
2. `for` loops
3. `while` loops
4. `pass`
5. `break` and `continue`
6. Ternary expressions (inline if). Simply put, this is `if/else` in one line. *Ternary* or *triary* is an adjective meaning "composed of three items".

## 1. `if / elif / else`

Python checks conditions top to bottom and runs the **first** block that is `True`. 

```python
if condition:
    # runs if condition is True
elif other_condition:
    # runs if the first was False, this is True
else:
    # runs if none of the above were True
```

In [ ]:
temperature = 18

if temperature >= 25:
    print("Warm — maybe shorts weather.")
elif temperature >= 10:
    print("Mild — a light jacket should do.")
else:
    print("Cold — dress up properly.")

In [ ]:
# You can chain as many elif branches as you need
day = "Monday"

if day == "Monday":
    print("Start of the week.")
elif day == "Wednesday":
    print("Halfway there.")
elif day == "Friday":
    print("Weekend soon!")
else:
    print(f"{day} — just another day.")

### Combining conditions with `and`, `or`, `not`

In [ ]:
is_raining = False
has_umbrella = False

if is_raining and not has_umbrella:
    print("You're going to get wet.")
elif is_raining and has_umbrella:
    print("You're prepared.")
else:
    print("No rain, no worries.")

---
## 2. `for` loops

A `for` loop iterates over any *sequence* — a list, a string, a range, etc.

```python
for item in sequence:
    # runs once for each item
```

In [ ]:
cities = ["Stockholm", "Gothenburg", "Malmö", "Uppsala"]

for city in cities:
    print(f"Hello from {city}!")

In [ ]:
# range() when you need a counter
for n in range(1, 6):
    print(f"Step {n}")

In [ ]:
# Looping over a list of dicts — each dict is like a row of data
people = [
    {"name": "Noah",  "age": 28},
    {"name": "Liam", "age": 17},
    {"name": "Alma", "age": 34},
]

for person in people:
    status = "adult" if person["age"] >= 18 else "minor"
    print(f"{person['name']} is {person['age']} — {status}")

In [ ]:
# enumerate() gives you index + value at the same time
fruits = ["apple", "banana", "cherry"]

for i, fruit in enumerate(fruits):
    print(f"{i}: {fruit}")

In [ ]:
# meet condition then add to new list
fruits = ["apple", "banana", "cherry"]
fruit_delivered = "apple"
fruit_to_eat = []

for fruit in fruits:
    if fruit_delivered == fruit:
        fruit_to_eat.append(fruit)

---
## 3. `while` loops

A `while` loop keeps going as long as a condition is `True`.  
Use it when you don't know in advance how many iterations you need.

```python
while condition:
    # keeps running as long as condition is True
```

In [ ]:
# Count down from 5
countdown = 3

while countdown > 0:
    print(countdown)
    countdown -= 1

print("Go!")

In [ ]:
# Keep trying until we get a valid answer
# (simulating responses rather than using input())
responses = ["maybe", "", "yes"]
accepted = ["yes", "no"]

i = 0
answer = responses[i]

while answer not in accepted:
    print(f"'{answer}' is not valid. Try again.")
    i += 1
    answer = responses[i]

print(f"Got a valid answer: '{answer}'")

> ⚠️ <font color=DeepPink>**Watch out for infinite loops!** Always make sure the condition can eventually become `False`, or use a `break`.</font>

---

## 4. `pass`

`pass` is a no-op — it does nothing. It's a placeholder for when Python *requires* a code block but you haven't written it yet.

```python
if condition:
    pass  # placeholder — does nothing
```

In [ ]:
# Useful when sketching out structure before filling in logic
def greet_user(name):
    pass  # TODO: write this later

# Also fine in branches you haven't handled yet
score = 42

if score >= 90:
    print("Excellent!")
elif score >= 60:
    pass  # handle this case later
else:
    print("Needs improvement.")

---

## 5. `break` and `continue`

- **`break`** — exit the loop immediately
- **`continue`** — skip the rest of this iteration and go to the next one

```python
for item in sequence:
    if condition:
        break      # exit the loop entirely
    if other_condition:
        continue   # skip to the next iteration
```

In [ ]:
# break: stop as soon as we find what we're looking for
names = ["Alice", "Bob", "Charlie", "Diana", "Eve"]

for name in names:
    if name == "Charlie":
        print(f"Found Charlie! Stopping.")
        break
    print(f"Not Charlie: {name}")

In [ ]:
# continue: skip missing values, process the rest
values = [10, None, 5, None, 8, 3]

total = 0
skipped = 0

for v in values:
    if v is None:
        skipped += 1
        continue
    total += v

print(f"Total: {total}  |  Skipped: {skipped} missing values")

---

## 6. Ternary expressions (inline `if`)

A compact way to write a simple if/else on a single line:

```python
value_if_true  if  condition  else  value_if_false
```

or even simpler:

```python
value = x  if condition  else  y
```

In [ ]:
age = 20
label = "adult" if age >= 18 else "minor"
print(label)

In [ ]:
# Works well inside a loop
scores = [88, 45, 72, 33, 91, 60]

for score in scores:
    result = "Pass" if score >= 70 else "Fail"
    print(f"{score}  →  {result}")

In [ ]:
# And inside a list comprehension — a very common Python pattern
results = ["Pass" if score >= 50 else "Fail" for score in scores]
print(results)

💡 That last cell combines a **ternary expression** with a **list comprehension**. You'll see this pattern a lot once we get into Pandas — for now, just notice that it exists.

## BREAK TIME 🐍

>I asked my code to stop looping.<br>
>*It said: "I'll get around to it."*

## A First Look at Data Workflow

With these basics (before pandas and other packages), you can already do meaningful data work using just lists of dicts, comprehensions, and built-ins. This is also the mental model pandas builds on.

Here is a small end-to-end example: load, clean, filter, aggregate, and report.

💡 Before we formally work through Functions ``def`, can you see what problem below data workflow might have?

In [ ]:
# --- Raw data (as you might receive from an API or CSV) ---
raw_data = [
    {"region": "North", "product": "Widget A", "revenue": "120000", "cost": "80000"},
    {"region": "South", "product": "Widget B", "revenue": "85000",  "cost": "60000"},
    {"region": "North", "product": "Widget C", "revenue": None,     "cost": "40000"},
    {"region": "East",  "product": "Widget A", "revenue": "200000", "cost": "130000"},
    {"region": "South", "product": "Widget C", "revenue": "30000",  "cost": "20000"},
]

# --- Step 1: Parse & clean ---
def parse_record(r):
    try:
        rev = float(r["revenue"])     # convert string to number
        cost = float(r["cost"])
        return {
            "region":  r["region"],
            "product": r["product"],
            "revenue": rev,
            "cost":    cost,
            "profit":  rev - cost,
            "margin":  (rev - cost) / rev
        }
    except (TypeError, ValueError):
        return None   # skip rows with missing/bad data

clean = [parse_record(r) for r in raw_data]
clean = [r for r in clean if r is not None]   # drop failed rows

print(f"Rows after cleaning: {len(clean)}")

# --- Step 2: Filter ---
high_margin = [r for r in clean if r["margin"] >= 0.30]
print(f"High-margin rows: {len(high_margin)}")

# --- Step 3: Aggregate by region ---
regions = {r["region"] for r in clean}

for region in sorted(regions):
    rows = [r for r in clean if r["region"] == region]
    total_rev = sum(r["revenue"] for r in rows)
    total_profit = sum(r["profit"] for r in rows)
    print(f"{region:8s}  Revenue: {total_rev:>10,.0f}  Profit: {total_profit:>10,.0f}")

# --- Step 4: Top product by revenue ---
top = sorted(clean, key=lambda r: r["revenue"], reverse=True)[0]
print(f"\nTop product: {top['product']} in {top['region']} — {top['revenue']:,.0f}")

## BREAK TIME 🐍

>A programmer's partner says: "Go to the store, get a gallon of milk, and if they have eggs, get a dozen."<br>
>*The programmer came home with 12 gallons of milk.*

## Python built-ins - CONTINUED from lecture 2

### Mutable vs Immutable Objects

This is one of the most common sources of unexpected bugs for newcomers. Understanding it now saves a lot of debugging later.

**Mutable** objects (`list`, `dict`, `set`) can be changed after creation.  
**Immutable** objects (`int`, `float`, `str`, `tuple`) cannot.

The subtle problem: assigning a mutable object to a new variable does **not** copy it. Both variables point to the **same object** in memory.

In [ ]:
# --- The problem ---
original = [10, 20, 30]
alias = original        # NOT a copy — both point to the same list

alias.append(99)
print(original)         # [10, 20, 30, 99] — original was changed too!

# --- The fix: copy explicitly ---
original = [10, 20, 30]
copy = original.copy()  # or: list(original)  or  original[:]

copy.append(99)
print(original)         # [10, 20, 30]  — untouched
print(copy)             # [10, 20, 30, 99]

# Same issue with dicts
rec = {"name": "Alice", "score": 88}
rec_copy = rec.copy()
rec_copy["score"] = 0
print(rec)              # original unchanged

# Immutable: no such issue
a = "hello"
b = a
b = b.upper()           # creates a NEW string, does not modify a
print(a)                # 'hello' — unchanged

### `*args` and `**kwargs`

You will encounter these in library documentation and in functions designed to accept a flexible number of arguments.

- `*args` — collects any number of **positional** arguments into a **tuple**
- `**kwargs` — collects any number of **keyword** arguments into a **dict**

The names `args` and `kwargs` are conventions — the `*` and `**` are what matter.

In [ ]:
# *args — variable number of positional arguments
def total(*amounts):
    return sum(amounts)

print(total(100, 200))           # 300
print(total(10, 20, 30, 40))     # 100

# **kwargs — variable number of keyword arguments
def describe_record(**fields):
    for key, value in fields.items():
        print(f"  {key}: {value}")

describe_record(name="Widget A", revenue=50_000, region="North")

# In practice: you'll see these when calling pandas, matplotlib, etc.
# e.g. df.plot(kind="bar", title="Revenue", figsize=(10,5), color="steelblue")
# All those extra keyword arguments go into **kwargs inside the function.

### Further Reading (Lecture 2 - Python Built-ins)

| Topic | Link |
|-------|------|
| *args and **kwargs | https://realpython.com/python-kwargs-and-args/ |
| Mutable vs immutable | https://realpython.com/python-mutable-vs-immutable-types/ |

# 1D Data - See it the Way Python Sees It

Before we write functions, let's slow down just a bit to do a bit of **execution and tracing** togehter.

We will:

1. Look at an 1D (1-dimensional) data applied use with Python. We will see how a Folder Tree structure function is built.
2. Utilize `f-string` in for-loop to show us how Python script runs step-by-step. We use our Lecture 3 Control Flow | Exercise 5 — Aggregate by category (with missing data) as example.

What can be extra fun is that after Lecture 1, we worked on a **W13 Exercise - Execution amd State Tracing** with pen and paper. In today's lecture, we will work with script to achieve the same purpose.

## Function `print_tree()`

Here we will start to transition using Python libraries and packages. To run this function, we will use a standard Python library `pathlib`. It comes with Python and no additional installation needed.

To read more about `pathlib`, go to [W3Schools](https://www.w3schools.com/python/ref_module_pathlib.asp) for the shortest version. Or visit [Real Python](https://realpython.com/python-pathlib/) for more detailed info.

In [ ]:
from pathlib import Path

def print_tree(path, prefix=""):
    '''
    print a given folder's entire structure and underlyting files. 
    '''
    contents = sorted(Path(path).iterdir())
    for i, item in enumerate(contents):
        connector = "└── " if i == len(contents) - 1 else "├── "
        print(prefix + connector + item.name)
        if item.is_dir():
            extension = "    " if i == len(contents) - 1 else "│   "
            print_tree(item, prefix + extension)

In [ ]:
# Say that I want to print the folder content from this folder to check what I have published to our Teams channel:

print_tree("publish_teams")

In [ ]:
# Appear I am not pointing at the right level. I need to go up a level.
print(Path.cwd())          # where you are now
print(Path.cwd().parent)   # one level up

In [ ]:
print_tree(Path.cwd().parent.parent / "publish_teams")

In [ ]:
print(Path.cwd().parent.parent) # two levels up

**Does `pathlib` work for both Mac and Windows? - Yes**

`pathlib` handles the separator difference automatically:

- Mac/Linux: Path.cwd().parent → /Users/pia/project
- Windows: Path.cwd().parent → C:\Users\pia\project

You write the same code — Python figures out the OS underneath.

## Function `print_tree()` step-by-step

1. `Path(path).iterdir()` lists everything in the folder. `sorted()` puts them in alphabetical order.

In [ ]:
my_folder = Path.cwd().parent.parent / "publish_teams"
contents = sorted(Path(my_folder).iterdir())

contents # this is a 1-dimensional list

2. `enumerate()` provides both the **index** and the **item** at each step

In [ ]:
for i, item in enumerate(contents[0:3]):
    print(i, item)

3. Is it last content in folder?

In [ ]:
len(contents)
# if index which is 5 (0:4), is 5 - 1 = 4, use "└── ", else use "├── "

In [ ]:
"└── " if i == len(contents) - 1 else "├── "

In [ ]:
# for the first item, index is 0
"└── " if 0 == len(contents) - 1 else "├── "

In [ ]:
# for the last item, index is 4
"└── " if 5 == len(contents) - 1 else "├── "

In [ ]:
connector = "└── " if i == len(contents) - 1 else "├── "
print( connector + item.name) # would be the last content in list

In [ ]:
# Add a new folder
new_dir = Path.cwd().parent.parent / "publish_teams" / "W15"
if not new_dir.exists():
    new_dir.mkdir(parents=True, exist_ok=True)

In [ ]:
# Remove folder
import os

os.rmdir(Path.cwd().parent.parent / "publish_teams" / "W15")

# will get an access is denied

In [ ]:
# Add multiple folders
# base = Path.cwd().parent / "project_new"

base = "project_new"

folders = [
    base,
    base / "data",
    base / "data" / "raw",
    base / "data" / "processed"
]

for folder in folders:
    Path(folder).mkdir(parents=True, exist_ok=True)
    print(f"Created: {folder}")

## For-loop & `f-string`

To add `f-string` in a for loop at the right place is kinda like watching Python work through it - a.k.a. seeing data the wy python sees it.

It is also how *debugging* works conceptually. Whenever you're unsure what Python is doing inside a loop — add a print() with an f-string and watch the output. Remove it when you're done.

Below example is taken from *W14 Exercise - Control Flow | Exercise 5 — Aggregate by category (with missing data)*

There are more than one solution to this exercise. Here we use 2 different approaches and see how they arrive at the same results.

#### Option 1 Nested loop

First run the entire script. Then run the following step-wise script to see output - in such a way you can see what happens during the loop while it runs through elements one by one.

In [ ]:
# Run the script to see final results

products = [
    {"name": "Laptop",      "category": "Electronics", "units_sold": 120},
    {"name": "Desk Chair",  "category": "Furniture",   "units_sold": 45},
    {"name": "Headphones",  "category": "Electronics", "units_sold": 200},
    {"name": "Bookshelf",   "category": "Furniture",   "units_sold": 50},
    {"name": "Keyboard",    "category": "Electronics", "units_sold": None},
    {"name": "Desk Lamp",   "category": "Lighting",    "units_sold": None},
    {"name": "Monitor",     "category": "Electronics", "units_sold": 140},
    {"name": "Floor Lamp",  "category": "Lighting",    "units_sold": 60},
    {"name": "Webcam",      "category": "Electronics", "units_sold": 200},
]

# Step 1: find unique categories
categories = []
for p in products:
    if p["category"] not in categories:
        categories.append(p["category"])

# Step 2 & 3: aggregate per category
for category in categories:
    total = 0
    skipped = 0
    for p in products:
        if p["category"] == category:
            if p["units_sold"] is None:
                skipped += 1
                pass  # nothing to add — units_sold is missing
            else:
                total += p["units_sold"]
    print(f"{category:15s} - total units sold: {total:4d}    skipped: {skipped}")

In [ ]:
# Step 1: what happens under the hood
categories = []
for p in products:
    if p["category"] not in categories:
        categories.append(p["category"])
    print(f"Checked: {p['name']:12} | category: {p['category']:12} | categories so far: {categories}")

In [ ]:
# Step 2 & 3: what happens under the hood

for category in categories:
    total = 0
    skipped = 0
    print(f"\n--- outer loop: category = '{category}' ---")
    for p in products:
        if p["category"] == category:
            if p["units_sold"] is None:
                skipped += 1
                print(f"    {p['name']:12} → None, skipped")
            else:
                total += p["units_sold"]
                print(f"    {p['name']:12} → units_sold={p['units_sold']},  total so far={total}")
    print(f"→ result: {category:15s} total={total}, skipped={skipped}")

### Option 2 Generator Expression

- Created separate list for **clean** and **skipped** befor using Generator Expression to reach the same result as option 1.
- Then use generator expression to aggregate categorical subtotals.

In [ ]:
products = [
    {"name": "Laptop",      "category": "Electronics", "units_sold": 120},
    {"name": "Desk Chair",  "category": "Furniture",   "units_sold": 45},
    {"name": "Headphones",  "category": "Electronics", "units_sold": 200},
    {"name": "Bookshelf",   "category": "Furniture",   "units_sold": 50},
    {"name": "Keyboard",    "category": "Electronics", "units_sold": None},
    {"name": "Desk Lamp",   "category": "Lighting",    "units_sold": None},
    {"name": "Monitor",     "category": "Electronics", "units_sold": 140},
    {"name": "Floor Lamp",  "category": "Lighting",    "units_sold": 60},
    {"name": "Webcam",      "category": "Electronics", "units_sold": 200},
]

# Step 1: create unique categories using set
categories = {p["category"] for p in products}

# Step 2: create separate list using if/pass/else for p["units_sold"] is None or not
products_clean = []
products_skipped = []

for p in products:
    if p["units_sold"] is None:
        products_skipped.append(p)
    else:
        products_clean.append(p)

# Step 3: count categories with skipped rows
category_skipped = [{"category":p["category"], "skipped_rows":+1} for p in products_skipped]

# Step 4: 
for category in sorted(categories):
    rows = [p for p in products_clean if p["category"] == category]
    total_units = sum(p["units_sold"] for p in rows)
    skipped_rows = [p for p in category_skipped if p["category"] == category]
    skipped = sum(p["skipped_rows"] for p in skipped_rows)
    print(f"{category:15s} - total units sold: {total_units:>3,}    skipped: {skipped}")

In [ ]:
# Step 1: create unique categories using set
categories = {p["category"] for p in products}
print(categories)

In [ ]:
# Step 2: create separate lists using if/pass/else for p["units_sold"] is None 
# What happens under the hood

products_clean = []
products_skipped = []

for p in products:
    if p["units_sold"] is None:
        products_skipped.append(p)
        print(f"Skipped so far: {products_skipped}")
    else:
        products_clean.append(p)
        print(f"Cleaned so far: {products_clean}")

print(f"\nSkipped rows: {len(products_skipped)} | Cleaned rows: {len(products_clean)}")

In [ ]:
# Step 3: count categories with skipped rows
category_skipped = [{"category":p["category"], "skipped_rows":+1} for p in products_skipped]

category_skipped

In [ ]:
# Step 4 what happens under the hoold: watch each variable

for category in sorted(categories):
    print(f"\n--- category: {category} ---")
    
    # what rows are in this category after cleaning?
    rows = [p for p in products_clean if p["category"] == category]
    print(f"  rows found: {len(rows)}")
    for r in rows:
        print(f"    {r['name']:12} units_sold={r['units_sold']}")
    
    # what is the total?
    total_units = sum(p["units_sold"] for p in rows)
    print(f"  total_units: {total_units}")
    
    # how many were skipped?
    skipped_rows = [p for p in category_skipped if p["category"] == category]
    skipped = sum(p["skipped_rows"] for p in skipped_rows)
    print(f"  skipped: {skipped}")
    
    # final output — same as the clean version
    print(f"  → {category:15s} - total units sold: {total_units:>3,}    skipped: {skipped}")

# Lecture 4: Functions & Error Handling

Functions are one of the most important concepts in programming. They let you **package a block of code** so you can reuse it, keep your scripts clean, and avoid repeating yourself.

In programmable data analytics, functions are a great way to clean a column, apply a transformation pattern, or automate a report. 

We have seen and used Functions in earlier lectures. In this one, we will look at how the function syntax look and how to use them. 

**Topics in this notebook:**
1. What is a function and how to write one
2. Returning values
3. `=` & default arguments
4. `*args` and `**kwargs` — flexible arguments
5. Namespaces and scope
6. Anonymous functions (`lambda`)
7. Error handling (`try` / `except`)

Today's lecture notes are partially based on [*Python for Data Analysis, 3rd Edition*](https://wesmckinney.com/book/python-builtin#functions) by Wes McKinney — Chapter 3.2: Functions. 

After the main **functions** section, there is a block of **extra good-to-know Python Basics**. Originally they are part of lecture 1 course note. I moved them here because lecture 1 course material was already crowded and these concepts, esp. **16. Modules & Imports**, is great to read together wth Functions. Of course, if you prefer you can also move these extra blocks back to your own lecture 1 note *13.1.2 Python basics*.

## 1. What is a Function?

A function is a **named, reusable block of code**. You define it once, and call it as many times as you like.

**Syntax:**
```python
def function_name(arguments):
    # code block
    return result
```

- `def` — tells Python you're defining a function
- `function_name` — you choose this name (use lowercase with underscores, aka *snake_case*)
- `arguments` — fancy name for inputs the function receives. It's optional.
- `return` — optional output the function sends back

Think of a function like a **recipe** as in cooking recipe: it has a name, takes some ingredients (arguments), does something, and optionally produces something (a return value).

In [1]:
# The simplest possible function — no arguments, no return value
def say_hello():
    print("Hello!")

say_hello()  # Call the function

Hello!

In [2]:
# A function with an argument
def greet(name):
    print("Hello,", name)

greet("Pia")
greet("Fabian")

Hello, Pia
Hello, Fabian

> **Note:** Defining a function doesn't run it. You must **call** it with `function_name()` to execute the code inside.

## 2. Returning Values

So far our functions just print things. 

In real data work, you usually want a function to **give you back a value** you can use elsewhere. The **returned value** is often an object like a cleaned list, a dictionary of results, or later on, a full DataFrame.

That's what `return` does — it sends a value back to whoever called the function.

In [3]:
import sys
print(sys.executable)

c:\Users\CeciliaBack\OneDrive - Cecilia Back\BI-analytiker\BI Python\.venv\Scripts\python.exe

In [4]:
# In below example, we only print without return — result disappears after print
def add_no_return(a, b):
    print(a + b)  # this just prints, doesn't store the result

result = add_no_return(3, 4)  # result is None!
print("result is:", result)

7
result is: None

In [6]:
# Here we use return — we get the value returned every time we call the function with valid input
def add(a, b):
    return a + b

result = add(3, 4)  # result stores 7
print("result is:", result)


# Now we can use it!
print(result * 2)
print(add(10, add(3, 4)))  # functions inside functions

# This particular function works with any "addable" elements
result = add("Hello", "!")
print(result)

result = add("Hello", "!"*3)
print(result)

# Uncomment to run below and observe the TypeError message
result = add({"name":"Pia"}, {"name":"Fabian"})
print(result)

result is: 7
14
17
Hello!
Hello!!!

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [7]:
# Returning multiple values — Python packs them into a tuple
def min_max(numbers):
    return min(numbers), max(numbers)

low, high = min_max([4, 1, 9, 2, 7])
print("Min:", low)
print("Max:", high)

# Note again that unless the function defines input type, this function works also for other non-numericals
start, end = min_max(["k", "d", "y", "i", "o"])
print("Start:", start)
print("End:", end)

# Define specific numerical types
def min_max_num(numbers:int):
    return min(numbers), max(numbers)

low_int, high_int = min_max_num([4, 1, 9, 2, 7])
print("Min number:", low_int)
print("Max number:", high_int)

# What does you think below would return?
low_float, high_float = min_max_num([4.6, 1.2, 9.7, 2, 7])
print("Min number:", low_float)
print("Max number:", high_float)
print(type(low_float))

Min: 1
Max: 9
Start: d
End: y
Min number: 1
Max number: 9
Min number: 1.2
Max number: 9.7
<class 'float'>

> **Rule of thumb:** If you'll need the result later (store it, pass it on, compare it), use `return`. If you just want to display something right now, use `print`.

## 3. `=` & Optional Argument's Default Value

To explain how this work, let's use earlier functions as examples. 

Below partially-shown functions require arguments as such. All must be entered, otherwise there will be errors.

```python
def add(a, b)
#       -  -
#       required, required

def min_max(numbers)
#           -------
#           required
```

Compare to below modifications:

```python
def add(a, b, unit_of_measure="piece/s")
#       -  -  ^^^^^^^^^^^^^^^^^^^^^^^^
#       required, required, optional with default value (use `=` to define)
```

In [8]:
def add(a:int, b:int, unit_of_measure="pieces"):
        return(f"{a + b} {unit_of_measure}")

result = add(3, 4)  # result takes default value for u_o_m
print(f"We have in total {result} in stock from both warehouses.")

result = add(2, 3, "boxes")  # result takes input value instead for u_o_m
print(f"We have in total {result} of tomato sauce counting both in the kitchen and the summer house.")

We have in total 7 pieces in stock from both warehouses.
We have in total 5 boxes of tomato sauce counting both in the kitchen and the summer house.

To summarize: you can give function's optional arguments **default values**. If the caller doesn't provide that argument (input), the default value is used. This makes functions more flexible while explicit at the same time.

Here the **sequence of arguments defined** is very imporant:

- Defaults (optional arguments) come after required arguments in the function definition.
- Default values for optional arguments must use `=` to indicate they are optional.

In addition:

- You can use `optional_argument_1=None`: used when the feature is off by default.
- You can use `optional_argument_1=True / False`: used it's a toggle with a natural default state.

In [9]:
# currency is optional — defaults to "SEK" if not provided
def format_price(amount, currency="SEK"):
    return f"{amount:.2f} {currency}"

print(format_price(1500))          # uses default
print(format_price(1500, "EUR"))   # override the default
print(format_price(1500, "USD"))   # another override

1500.00 SEK
1500.00 EUR
1500.00 USD

In [10]:
# Real-world example: cleaning a text column
# Default behavior is to strip whitespace and lowercase — but both are optional
def clean_text(text, strip=True, lowercase=True):
    if strip:
        text = text.strip()
    if lowercase:
        text = text.lower()
    return text

print(clean_text("  Stockholm  "))           # both defaults apply
print(clean_text("  Stockholm  ", lowercase=False))  # keep original case
print(clean_text("  Stockholm  ", strip=False))       # keep spaces

stockholm
Stockholm
  stockholm

> **A good practice:** pass arguments (*in plain english: enter input for arguments*) by variable **names** — this makes code easier to read and avoids mistakes with argument order because Python reads the **positions of arguments** not the content. See below examples:

In [11]:
def register_student(name, age, course, active=True):
    print(f"{name}, age {age}, enrolled in {course}, active: {active}")

# ❌ Positional entry — this won't throw an error technically, but it is wrong
print("\n------ wrong data entered at wrong position ------")
register_student("BI & Python", 28, "Pia" )

print("\n------ corret & easy to read ------")
# ✅ Keyword — order doesn't matter, meaning is clear
register_student(name="Pia", age=28, course="BI & Python")

# ✅ Also fine — mix positional for obvious args, keyword (variable name) for the rest
register_student("Pia", 28, course="BI & Python", active=False)

------ wrong data entered at wrong position ------
BI & Python, age 28, enrolled in Pia, active: True

------ corret & easy to read ------
Pia, age 28, enrolled in BI & Python, active: True
Pia, age 28, enrolled in BI & Python, active: False

## 4. Flexible Arguments: `*args` and `**kwargs`

Sometimes you don't know in advance how many arguments will be passed. Python has two special syntaxes for this:

- `*args` — collects any number of **positional** arguments into a tuple
- `**kwargs` — collects any number of **keyword** arguments into a dictionary

The names `args` and `kwargs` are just conventions — the `*` and `**` are what matter.

> **A heads-up:** It's fine to just know about `*args` and `**kwargs` for now. Especially `**kwargs` is more advanced in function writing. Let's look into this later in our course when we have actual examples suitable to explain and demostrate how to use.

In [12]:
# *args — accept any number of values
def total(*args):
    print("Received:", args)  # args is a tuple
    return sum(args)

print(total(10, 20))
print(total(10, 20, 30, 40, 50))

Received: (10, 20)
30
Received: (10, 20, 30, 40, 50)
150

In [13]:
# **kwargs — accept any number of named values
def show_info(**kwargs):
    print("Received:", kwargs)  # kwargs is a dictionary
    for key, value in kwargs.items():
        print(f"  {key}: {value}")

show_info(name="Pia", department="Finance", city="Stockholm")

Received: {'name': 'Pia', 'department': 'Finance', 'city': 'Stockholm'}
  name: Pia
  department: Finance
  city: Stockholm

## BREAK TIME 🐍

> Why do functions make great friends? <br>
> *They always know what to return.*

## 5. Namespaces and Scope

This is one of those topics that may be confusing at beginning but is very important once you write bigger programs.

**Scope** = where a variable "lives" and can be accessed.

- Variables created **inside** a function are **local** — they only exist inside that function.
- Variables created **outside** functions are **global** — they exist everywhere.

Python always looks for a variable in the **local scope first**, then the global scope.

In [14]:
# x inside the function is LOCAL — a different x than outside
x = 100  # global x

def change_x():
    x = 999  # local x — only lives inside this function
    print("Inside function, x =", x)

change_x()
print("Outside function, x =", x)  # still 100 — global was NOT changed

Inside function, x = 999
Outside function, x = 100

In [15]:
# The function CAN read a global variable (but shouldn't change it this way)
company_name = "Acme AB"

def get_greeting():
    return f"Welcome to {company_name}"  # reads the global

print(get_greeting())

Welcome to Acme AB

In [17]:
# Accessing a local variable OUTSIDE its function → NameError
def make_greeting():
    greeting = "Hello!"  # local variable.
    return greeting

make_greeting()
print(greeting)  # ← uncomment this to see NameError

NameError: name 'greeting' is not defined

> **Key insight:** Functions should work with their **inputs and outputs**, not rely on or change global state. This makes them predictable and reusable.

## 6. Anonymous Functions: `lambda`

A `lambda` is a **small, one-line function without a name**. It's useful when you need a quick function to pass into another function — like when sorting or filtering data.

**Syntax:**
```python
lambda arguments: expression
```

A lambda always returns the result of the expression — no `return` keyword needed.

In [18]:
# Regular function vs lambda — same result, different style
def double(x):
    return x * 2

double_lambda = lambda x: x * 2

print(double(5))
print(double_lambda(5))

10
10

In [19]:
# A very common use: sorting by a custom key
products = [
    {"name": "Laptop",  "price": 12000},
    {"name": "Mouse",   "price": 299},
    {"name": "Monitor", "price": 4500},
]

# Sort by price using a lambda
sorted_products = sorted(products, key=lambda p: p["price"])
sorted_products_desc = sorted(products, key=lambda p: p["price"], reverse=True)

print("--- sorted in ascending order ---")
for p in sorted_products:
    print(p["name"], "—", p["price"])

print("\n--- sorted in descending order ---")
for p in sorted_products_desc:
    print(p["name"], "—", p["price"])

--- sorted in ascending order ---
Mouse — 299
Monitor — 4500
Laptop — 12000

--- sorted in descending order ---
Laptop — 12000
Monitor — 4500
Mouse — 299

In [20]:
# Another common use: filtering with a lambda
prices = [299, 12000, 4500, 89, 7800, 150]

expensive = list(filter(lambda p: p > 1000, prices)) 
# above can also be achieved with a list comprehension, such as expensive = [p for p in prices if p > 1000]
print("Expensive items:", expensive)

Expensive items: [12000, 4500, 7800]

In [ ]:
# Filter restaurants by minimum rating — lambda as the condition
restaurants = [
    {"name": "Pasta Palace", "rating": 4.5},
    {"name": "Burger Barn",  "rating": 3.8},
    {"name": "Sushi Spot",   "rating": 4.9},
]

top_rated = [r for r in restaurants if r["rating"] >= 4.0]
top_rated_names = list(map(lambda r: r["name"], top_rated))
print("Top rated:", top_rated_names)

> **When to use lambda vs `def`?**
> - Use `lambda` for quick, throwaway functions — especially as arguments to `sorted()`, `filter()`
> - Use `def` for anything you'll name, reuse, or that has more than one line of logic
>
> In pandas, `lambda` can be used conveniently so — e.g. `df["col"].apply(lambda x: x * 1.25)`

---

## 7. Error Handling: `try` / `except`

When working with real data, errors happen — missing values, wrong data types, files that don't exist. Instead of letting your script crash, you can **catch errors** and handle them gracefully.

**Syntax:**
```python
try:
    # code that might fail
except SomeError:
    # what to do if it fails
```

In [ ]:
# Without error handling — this crashes the whole script
def divide(a, b):
    return a / b

# divide(10, 0)  # ← uncomment to see ZeroDivisionError

In [ ]:
# With error handling — we catch the error and decide what to do
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        print("Warning: cannot divide by zero, returning None")
        return None

print(safe_divide(10, 2))
print(safe_divide(10, 0))

In [ ]:
# Catching multiple error types
def parse_number(value):
    try:
        return float(value)
    except ValueError:
        print(f"Could not convert '{value}' to a number")
        return None
    except TypeError:
        print(f"Wrong type: {type(value)}")
        return None

print(parse_number("3.14"))   # works
print(parse_number("hello"))  # ValueError
print(parse_number(None))     # TypeError

In [ ]:
# else and finally — advanced but useful
# else: runs only if NO error occurred
# finally: ALWAYS runs, regardless of error

def load_value(data, key):
    try:
        result = data[key]
    except KeyError:
        print(f"Key '{key}' not found")
        result = None
    else:
        print(f"Successfully retrieved: {result}")
    finally:
        print("Done.")  # always runs
    return result

sales = {"Q1": 150000, "Q2": 210000}
load_value(sales, "Q1")
print() # print() with no arguments simply print an empty line - a formatting trick for better readability.
load_value(sales, "Q3")

### Errors

| Error | When it happens | Example |
|---|---|---|
| `ValueError` | Wrong value for the type | `float("N/A")` |
| `TypeError` | Wrong type entirely | `float(None)` |
| `KeyError` | Dict key doesn't exist | `row["revenue"]` when key is missing |
| `IndexError` | List index out of range | `my_list[99]` on a short list |
| `AttributeError` | Method doesn't exist on that type | `"hello".upper` without `()` |
| `FileNotFoundError` | File path is wrong or missing | `pd.read_csv("wrong_path.csv")` |
| `ZeroDivisionError` | Dividing by zero | `revenue / covers` when covers is 0 |

<br>

> You don't need to memorise these. Python always tells you the error type in the traceback — the skill is **recognising** them when they appear, not recalling them from memory.

## Putting It All Together: A Mini Data Pipeline

Here's a small example combining functions, defaults, lambda, and error handling — the kind of code you may actually write in data projects.

In [ ]:
# Raw sales data — messy, as usual in real life
raw_data = [
    {"product": "  Laptop ? ", "revenue": "120000"},
    {"product": "MoUSe",      "revenue": "N/A"},
    {"product": "MONITOR#",    "revenue": "45000"},
    {"product": "keyboard! ",  "revenue": "8500"},
]

# Step 1: Clean product names
# use built-in regex package to clean
import re 

def clean_name(name):
    name=re.sub("[!#?]", "", name)
    # below shows how the functions are chained up with . instead of having two lines of code
    return name.strip().title()

# Step 2: Safely parse revenue
# Below default = 0 is a more elegant way than the if/else we used earlier
def clean_revenue(value, default=0):
    try:
        return float(value)
    except ValueError:
        print(f"  Could not parse revenue '{value}', using {default}")
        return default

# Step 3: Process the dataset
def process_sales(data):
    cleaned = []
    for row in data:
        cleaned.append({
            "product": clean_name(row["product"]),
            "revenue": clean_revenue(row["revenue"])
        })
    return cleaned

# Step 4: Sort by revenue using lambda
result = process_sales(raw_data)
result_sorted = sorted(result, key=lambda r: r["revenue"], reverse=True)

print("\nFinal cleaned & sorted data:")
for row in result_sorted:
    print(f"  {row['product']:12} — {row['revenue']:>10,.0f} SEK")

## Quick Reference

| Concept | Syntax | When to use |
|---|---|---|
| Define a function | `def name(args):` | Any reusable block of logic |
| Return a value | `return value` | When you need to use the result elsewhere |
| Default argument | `def f(x, y=10):` | When an argument is often the same value |
| Any number of args | `def f(*args):` | Variable number of positional arguments |
| Named extra args | `def f(**kwargs):` | Variable number of keyword arguments |
| One-liner function | `lambda x: x * 2` | Quick functions passed to sort/filter/apply |
| Handle errors | `try: ... except X:` | When something might fail (bad data, missing files) |

## Further Reading

- McKinney, *Python for Data Analysis*, Ch. 3 — Functions: https://wesmckinney.com/book/python-builtin#functions
- Real Python — Defining Functions: https://realpython.com/defining-your-own-python-function/
- Real Python — Python Exceptions: https://realpython.com/python-exceptions/
- W3Schools — Python Functions: https://www.w3schools.com/python/python_functions.asp

## BREAK TIME 🐍

>Why did the function break up with the variable? <br>
>*It had too many arguments*.

## Extras: lecture 1 (CONT.) - Python Basics Orientation 

Following are originally part of Lecture 4 course material. Because lecture 1 ran shorter than planned, they are now included in lecture 4. Some of below are worked through in greater detail today. Yet, they are great to be read together with lecture 1 notes for a mental orientation and reflection.

### 15. Error Handling

Use `try / except` to catch errors gracefully instead of letting the program crash. You can catch specific exception types for precise control.

In [ ]:
# Without handling — this would crash:
# print(10 / 0)

# With handling
try:
    result = 10 / 0
except ZeroDivisionError:
    print("Cannot divide by zero.")

# Catching multiple exception types
def safe_parse(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return None

print(safe_parse("3.14"))   # 3.14
print(safe_parse("N/A"))    # None
print(safe_parse(None))     # None

### 16. Modules & Imports

A **module** is a `.py` file containing reusable code. Python's standard library has modules for math, dates, files, and much more. Third-party packages (like pandas) are installed via `pip`.

Three common import styles:

```python
import math                  # import the whole module
from math import sqrt, pi    # import specific names
import numpy as np           # import with a short alias
```

Sometimes, it is assumed that while a package is a collection of modules, a library is a collection of packages.

**PyPi** (Python Package Index) is the repo for Python packages. Head over to[https://pypi.org/](https://pypi.org/) and search for **NumPy** and **pandas** to see for yourself.

In [ ]:
import math
from datetime import date

print(math.sqrt(144))        # 12.0
print(math.pi)               # 3.14159...
print(date.today())          # today's date

### 17. Lambda Functions

Lambda functions are small anonymous functions created with the `lambda` keyword. Syntax: `lambda arguments: expression`.

In [ ]:
# A lambda that takes two arguments and returns their sum
add = lambda x, y: x + y
result = add(5, 3)
print(result)  # 8

### 18. OOP — Classes & Objects

OOP stands for Object-Oriented Programming.

A **class** is a blueprint for creating objects. An **object** is an instance of a class.

In [ ]:
class Dog:
    # Constructor — initializes the object
    def __init__(self, name):
        self.name = name

    # Object method
    def bark(self):
        print(f"{self.name} says woof!")

# Create an instance of Dog
my_dog = Dog("Rex")
my_dog.bark()  # Call the object's method

### 19. Commonly Used Built-in Functions

Python provides powerful built-in functions that can be used directly without importing any module.

#### Math & Numeric

| Function | Description |
|---|---|
| `abs(x)` | Absolute value |
| `round(x, n)` | Round to `n` decimal places |
| `max(iterable)` | Largest item |
| `min(iterable)` | Smallest item |
| `sum(iterable)` | Sum of all items |
| `pow(x, y)` | `x` raised to the power `y` |

#### Sequence Operations

| Function | Description |
|---|---|
| `len(obj)` | Length of an object |
| `sorted(iterable)` | Return a sorted list |
| `reversed(sequence)` | Return a reversed iterator |
| `enumerate(iterable)` | Return index-value pairs |
| `zip(*iterables)` | Pair up elements from multiple iterables |
| `map(func, iterable)` | Apply a function to each element |
| `filter(func, iterable)` | Filter elements by a function |

#### Input & Output

| Function | Description |
|---|---|
| `print(*objects)` | Print to the console |
| `input(prompt)` | Read a string from the user |

#### Other Useful Functions

| Function | Description |
|---|---|
| `type(obj)` | Return the type of an object |
| `isinstance(obj, type)` | Check if an object is of a given type |
| `range(start, stop, step)` | Generate a sequence of numbers |
| `list()` / `tuple()` / `dict()` / `set()` | Type conversion |
| `int()` / `float()` / `str()` | Numeric/string conversion |
| `id(obj)` | Return the memory address of an object |

In [ ]:
numbers = [3, 1, 4, 1, 5, 9, 2, 6]

print("Max:", max(numbers))
print("Min:", min(numbers))
print("Sum:", sum(numbers))
print("Sorted:", sorted(numbers))
print("Length:", len(numbers))

# enumerate example
for idx, val in enumerate(['a', 'b', 'c']):
    print(f"  index {idx} → {val}")

# Lecture 5 Part 1 - Python Packages useful for BI

## Structured by Workflow

We introduce the Python data analytics *package collection* grouped by **what you are trying to do** typically along a data analytics workflow. This structure draws inspiration from [`R` Tidyverse package collection](https://tidyverse.org/packages/). 

It's good to keep in mind that this structure helps us to learn. The structure is not to restrict or limit the packages for what they are capable of. The packages (or modules, frameworks) listed here are not the only ones for these tasks. More to explore as the world of programmable data analytics expands at your fingertips. Please feel free to explore and learn about other packages even after our course finishes.

For our course, we will mainly learn about `pandas`, which is built upon `numpy` and `matplotlib`. 

| Workflow Phase | Python Packages (commonly-used for DA & also DS) |
|---|---|
| **Import** | `pandas`, `openpyxl`, `sqlalchemy`|
| **Wrangle** | `pandas`, `pyarrow`, `duckdb` |
| **Visualise** | `matplotlib`, `seaborn`, `plotly`, `streamlit`|
| **Program** | built-ins, `itertools`, `pathlib`, `re` |
| **Model** | `scikit-learn`, `statsmodels` |

You can choose to install multiple packages in one go if you'd like to. 

```python
# run below in Python REPL or Jupyter Notebook to install packages to your chosen Python kernel - your Python .venv

%pip install pandas matplotlib seaborn plotly scikit-learn
```

However, I'd like to invite you to **slow down and have a look first** at what's been installed already - as a refresher for the `help()` and `dir()` functions we used earlier in the course.

## *Code to Learn* about a Package

### Installed or Not

**Before installing**, it's good to read a package's official documentation, including installation section. Also good to read some simple tutorial to understand what's it for first.

**When about to install**, we can *run code and ask Python* if we already have the package installed and perhaps which version it is. Remember our **Code to Learn** in week 13 lecture 2? 

Say that we want to ask if `pandas` is installed.

In [ ]:
# Wihtout needing to import pandas, simply use below to ask

help("pandas") # or help('pandas') 

# If already installed, the output shows help doc. If not, the output will say no documentation found.

In [ ]:
# If installed, one can for example check the module version.

import pandas as pd
print(pd.__version__)

In [ ]:
# Try on another module (or framework)

help("streamlit")

### A Quick Refresher on `help()`

Now we have learned and worked with Python for two weeks. Let's use `help()` again!

In [ ]:
# Just out of curisotiy, what happens if we ask help to describe help()
help(help())

In [ ]:
help("modules")

In [ ]:
help("symbols")

In [ ]:
help("topics")

In [ ]:
help("LISTS")

### A Quick Peek Using pip/shell

In [ ]:
help("pandas")

In [ ]:
# Similar to help("pandas") but different. Can you spot the difference?

%pip show pandas

### pip/shell vs. help()

**The difference below the two approaches are**:

- `%pip show pandas` is a **pip/shell command** that shows package metadata — version, author, install location, dependencies, etc. 
- `help('pandas')` uses **Python's built-in help system** and shows the module's docstring and public API — classes, functions, and their documentation.

More specifically:

- `%pip show pandas` reads from the package's dist-info **metadata** folder (e.g. `.venv/lib/pandas-2.x.x.dist-info/`). This is pure packaging metadata written by pip at install time — it knows nothing about the code itself.
- `help('pandas')` reads from the actual **source code** inside `.venv/lib/pandas/` — specifically the docstrings embedded in the .py files.

Now open your `.venv` folder and look for the following.

```bash
.venv/lib/
├── pandas/                  ← help() reads from here (source + docstrings)
│   ├── __init__.py
│   ├── core/
│   └── ...
└── pandas-2.x.x.dist-info/ ← pip show reads from here (install metadata)
    ├── METADATA
    ├── RECORD
    └── ...
```

> Now you know **"where does pandas live?" in this `.venv`** on your laptop.

> For the learning scale we have now, `pip` is a good package manager to get familiar with. Later on for lager projects, `uv` is a more modern package manager to manage dependencies and complex environments at scale.

### A Bit More on `%pip`

The `%` used before `pip` is a special construct by IPython. It works in an interactive Python interpreter, such as Python REPL inside VSCode. It also works for Jupyter Notebook. 

It's a topic that's slightly outside our main topics in this course. If interested, please read more about:

- `%` and `%%` in IPython Build-in magic commands: https://ipython.readthedocs.io/en/stable/interactive/magics.html
- `pip` in pip Commands at pip documentation: https://pip.pypa.io/en/stable/cli/

Below are some practical examples for us to quickly access Python packages metadata.

In [ ]:
# Use %pip to peek all the installed packages in this .venv and packages versions. This is essentially the same as using terminal cmd tool. 

# please note list here refers to the list of modules installed. Different from the above help("LISTS") where we read Python's help doc on the topic LISTS.

%pip list

In [ ]:
# To output the package versions in the format ready for export

%pip freeze

In [ ]:
# Write the package and version as a requirement.txt to a designated location
# To run below, you will need to use your own path to specify location in relation to your .venv

%pip freeze>requirements.txt

## What's Inside a Package

Below we will use `pandas` as an example.

### 1. `dir()` lists all inside

We start with `dir()` which lists all attributes and methods inside a package.

In [ ]:
import pandas as pd

dir(pd)

In [ ]:
# a cleaner look using for-loop

for x in dir(pd):
    print(x)

In [ ]:
# an oneliner list comprehension if one condition

pandas_read = [x for x in dir(pd) if x.startswith("read")]
pandas_read

### 2. `inspect` module 

`dir()` returns everything (classes, constants, submodules etc.). If you want to see only functions or methods, you can use built-in `inspect` module.

In [ ]:
# First let's have a look at inspect module

help("inspect")

In [ ]:
import inspect
import pandas as pd

# Use inspect.getmembers(obj) to view pandas top 5 elements
inspect.getmembers(pd)[0:5]

In [ ]:
# Above output shows the returned output is a list with tuples. Each tuple contains 2 elements, which are name, obj in below list comprehension

functions = [name for name, obj in inspect.getmembers(pd) if inspect.isfunction(obj)]
functions

### 3. Read about a function

In [ ]:
# read help for the entire documentation about a specific function. Please note the optional `=` arguments and their default values.

help(pd.read_csv)

In [ ]:
# Note different representation of similar info under specific headings, such as Signature, Docstring.

#pd.read_csv?

In [ ]:
# Note varied color representation and different indentation compared to the above ?

#pd.read_csv??

In [ ]:
# If only want to see Docstring for a function, it is stored in `__doc__`. pandas.read_csv docstring is quite long regardless.

print(pd.read_csv.__doc__)

## A .drawio Diagram

Install VSCode extension **Draw.io Integration by Henning Dieterichs** to open `15.1.1 Python packages for DA.drawio` to view a mindmap style workflow and packages overview. 

If interested, you can explore the specifics mentioned in .drawio diagram in your Python REPL or directly here in the Notebook.

In [ ]:
help("numpy")

In [ ]:
help("matplotlib")

# Lecture 5 Part 2 - Intro to Pandas

Based on *Python for Data Analysis, 3rd Edition* by Wes McKinney — [Chapter 4 NumPy Basics](https://wesmckinney.com/book/numpy-basics) and [Chapter 5: Getting Started with pandas](https://wesmckinney.com/book/pandas-basics)

## Before Pandas There Was NumPy

As mentioned earlier, pandas was built upon NumPy (package name spelled as numpy). NumPy is an essential Python library. In addition to pandas — which is built upon it — and Matplotlib, which integrates tightly with it, TensorFlow and scikit-learn use NumPy arrays as inputs. The latter two are the essentials in the world of machine learning.

We will not go into NumPy arrays here and now. Just a small bridge section for us to make a ***technical transition*** from 1D to 2D arrays. 2D NumPy array is the core component underlying pandas DataFrame, which for us is also read as Tabular Data Tables.

In below illustration, we see that **pandas DataFrame can be considered as 2D arrays + labels**.

![NumPy 2D arrays](image/lecture_5_numpy_to_pandas_bridge.png)

For NumPy, there are also 3D and 4D arrays. Do make your time to find out what these are and what they may be used for.

Fow now, let's continue with a selected few examples to get us warmed up for NumPy arrays in 2D before we move on to pandas DataFrame world.

Exampls are taken directly from Wes Mckinney's book chapter 4 NymPy Basics: Arrays and Vectorized Computation.

### NumPy ndarrays

**ndarray** stands for N-dimensional array object in NumPy. This feature enables larger scale mathematical calculation.

In [ ]:
import numpy as np

# create and show 1D array
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

In [ ]:
# create and show 2D array, note that it's without labels
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

# take a look at it
arr2

In [ ]:
print(type(arr2))  # check type
print(arr2.ndim)  # how many dimensions?
print(arr2.shape)  # array in what shape (for 2D, it is as in row x column)?

In [ ]:
print(arr2)
print(f"There are {arr2.ndim} dimensions in the array above")
print(f"It has data type: {arr2.dtype}")
print(
    f"This array has a shape of {arr2.shape[0]} x {arr2.shape[-1]} as it has {arr2.shape[0]} rows x {arr2.shape[-1]} columns"
)

In [ ]:
# Methematical calculation on the array

arr2 * 3

### ndarray Data Type 

One array can be created with an explicitly specified data type `dtype`. However, one cannot mix data types inside an array. When ndarray is created, it can only hold a single data type.

In [ ]:
# compare the array datatypes

print(arr1.dtype)
print(arr2.dtype)

In [ ]:
arr_mix = np.array([[1, 2, 3, 4], ["a", "b", "c", "d"]])

arr_mix.dtype  # will return dtype('<U21') which indicates it's string of a certain length.

In [ ]:
# When we call arr_mix, we can see the integers are coerced into string type.

arr_mix

In [ ]:
# You can cast ndarray datatype with astype. Below we temporarily cast arr2 into a float64 type. See the decimal . indicating data type float?

print(arr2.astype(np.float64))

In [ ]:
# Compare to arr2 as is.

arr2

That's ndarrays for us now. We will not go deeper than this. Please do read Wes' book for a more comprehensive walkthroughs on NumPy basics and advanced NumPy.

## BREAK TIME 🐍

>I told my students to import summer heat. <br> 
>*They got a ModuleNotFoundError*.

## Pandas Basics - Part 1

In today's lecture, we will cover part of the pandas basics. The rest will be covered in Friday's lecture 6.

> 📖 **Before or after working with this notebook**, read the original at: https://wesmckinney.com/book/pandas-basics

**What we'll cover:**

1. The two core pandas objects: `Series` (1D) and `DataFrame` (2D)
2. Loading data — from a dict, CSV, and Excel
3. Inspecting a DataFrame
4. Selecting columns and rows
5. Cleaning data — the pandas way

We will make some reference to earlier course materials where we worked on above tasks *manually* with Python built-ins so you can compare the two.

### 1. The two core objects: Series and DataFrame

#### Series: 1D + label

A **Series** is a one-dimensional labelled array — think of it as a single column with an index and you can customize the index. Well, yes, this might be a bit confusing at the start.

Let's start from the more familar standard index as 0, 1, 2, ...

How we create a pandas.Series might remind you something similar: a Python list. The difference is that a Series naturally carries an **index** (labels for each position) without you calling it explicitly and it knows its **dtype** (the data type of its values - just like what we've seen in NumPy basics above).

Run code block below and observe returned output.

In [ ]:
import pandas as pd

# A Series from a list
revenues = pd.Series([182000, 95000, 28000, 61000])
revenues

In [ ]:
# Below are some of the pandas.Series.method you can use to call specific info. You can run help(pandas.Series.method) in Python REPL to read about these methods.

# print is convenient to see all output in one-go. It's also interesting to observe the output if no print is used.

print("dtype:", revenues.dtype)
print("values:", revenues.values)  # the underlying array
print("index:", revenues.index)  # the labels (0, 1, 2, 3 by default)

In [ ]:
revenues.dtype

In [ ]:
revenues.values

In [ ]:
revenues.index

While you can use the default index 0, 1, ..., it is also possible to label element in the Series as below

In [ ]:
# A Series with a custom index
revenues = pd.Series(
    [182000, 95000, 40040, 59780],
    index=["Pasta Palace", "Burger Barn", "Sushi Spot", "Taco Town"],
)
revenues

In [ ]:
# Above may look like a table, but not yet.

type(revenues)

# It's only rows got row label (customized index). This is still only 1D data without a column label.

In [ ]:
# try again to see the index

revenues.index # now with the labels

#### DataFrame: 2D + named columns

A **DataFrame** is a two-dimensional table — rows and named columns. We are very familiar with them. We've seen them in spreadsheets or a SQL table.

Each column in a DataFrame is a Series — if you pull a column out of a DataFrame, you get a Series back.

Now let's work with an example DataFrame.

### 2. Loading data

For learning purpose, we will work with loading data from CSVs.

Just to refresh our memory about how to create new directory using `Path` from `pathlib`, let's:

- create a DataFrame from a list with multiple dictionaries
- create a filepath where the DataFrame will be written into
- write it to csv we create above

In [ ]:
import pandas as pd
clean = [
    {"restaurant": "Pasta Palace",  "city": "Stockholm",  "revenue_sek": 182000, "covers": 210, "rev_per_cover": 866.7,  "rating": 4.5},
    {"restaurant": "Burger Barn",   "city": "Stockholm",  "revenue_sek":  95000, "covers": 180, "rev_per_cover": 527.8,  "rating": 3.8},
    {"restaurant": "Sushi Spot",    "city": "Copenhagen", "revenue_sek":  40040, "covers":  95, "rev_per_cover": 421.5,  "rating": 4.9},
    {"restaurant": "Taco Town",     "city": "Oslo",       "revenue_sek":  59780, "covers": 140, "rev_per_cover": 427.0,  "rating": None},
    {"restaurant": "Green Garden",  "city": "Oslo",       "revenue_sek":      0, "covers":  88, "rev_per_cover":   0.0,  "rating": 4.1},
    {"restaurant": "Burger Barn",   "city": "Copenhagen", "revenue_sek":  45045, "covers": 210, "rev_per_cover": 214.5,  "rating": None},
    {"restaurant": "Ramen House",   "city": "Stockholm",  "revenue_sek":  74000, "covers": None,"rev_per_cover":  None,  "rating": 4.2},
]

df = pd.DataFrame(clean)
df

In [ ]:
# I want to write DataFrame to a new subfolder data under W15
# Check your result after running below

df.to_csv("data/restaurants.csv", index=False)

In [ ]:
df_loaded = pd.read_csv("data/restaurants.csv")
df_loaded

### 3. Inspecting a DataFrame

Once the DataFrame is in memory, let's inspect it. 

Below DataFrame.method tell you quite a bit about the data.

- `shape`
- `dtypes`
- `head` & `tail`
- `describe`
- `isna`: pandas calls missing number NaN (Not a Number) same as None type, built-in.

In [ ]:
# Shape: (no. of rows, no. of columns)

df.shape

In [ ]:
# Indiviual column (a Series) data types

df.dtypes

In [ ]:
# top n rows, help(pd.DataFrame.head) tells us default n: int = 5

df.head(3)

In [ ]:
# last n rows, default n: int = 5

df.tail(2)

In [ ]:
# Summary statistics for numeric columns
df.describe()

In [ ]:
# Missing value counts on the entire DataFrame

df.isna()

# In Lecture 4 we dealt with None manually.
# Pandas calls missing values NaN (Not a Number) — same concept, built in.

In [ ]:
# We can also chain up methods to count — how many NaN per column?

df.isna().sum()

### 4. Selecting columns and rows

#### Column selection

A single column returns a **Series**. Multiple columns return a **DataFrame**.

This will feel familiar — selecting a key from a dict works the same way.

In [ ]:
# Single column — returns a Series

df["restaurant"]

In [ ]:
type(df["restaurant"])

In [ ]:
# Multiple columns — returns a DataFrame and often a subset

# Note the double brackets: 
# outer [] selects from df
# inner [] is the list of column names

df[["restaurant", "city", "revenue_sek"]]

#### Row selection with `.loc` and `.iloc`

| Method | Selects by | Example |
|--------|-----------|----------|
| `.loc` | **label** (index value or column name) | `df.loc[0]`, `df.loc[0, "city"]` |
| `.iloc` | **integer position** (0-based) | `df.iloc[0]`, `df.iloc[0, 1]` |

When the index is 0, 1, 2... (the default), `.loc` and `.iloc` look the same — but they're not. 

> **Rule of thumb**: use `.iloc` when you mean "position", `.loc` when you mean "label".

In [ ]:
# let's have a look at the DataFrame again, pay attention to the index per row

df

In [ ]:
df.iloc[0]  # select a row by position: index 0 (the first row)

In [ ]:
df.loc[0]   # identical result is returned because we haven't labeled our index

In [ ]:
# One can also choose to see a row as a row - this work for tables that are not so wide.

df.iloc[0:1]

In [ ]:
# Slicing — first three rows

df.iloc[0:3]

In [ ]:
# Select a specific cell: row 2, column "city"

df.loc[2, "city"]

In [ ]:
# same cell by position

df.iloc[2, 1]

### 5. Cleaning data — the pandas way

In earlier lectures, we did quite a few *manual* cleaning by writing functions and loops from Python built-ins. Pandas has built-in tools for most of these jobs.

Let's reload the *raw* data and clean it with pandas this time.

In [ ]:
# Raw data — same as Lecture 4
raw_data = [
    {"restaurant": "  pasta palace   ",  "city": "Stockholm",  "revenue": "182000",    "currency": "SEK", "covers": "210", "rating": "4.5"},
    {"restaurant": "Burger Barn  ",   "city": "Stockholm",  "revenue": "95000",     "currency": "SEK", "covers": "180", "rating": "3.8"},
    {"restaurant": "SUSHI SPOT",      "city": "Copenhagen", "revenue": "28000",     "currency": "DKK", "covers": "95",  "rating": "4.9"},
    {"restaurant": "taco town",       "city": " Oslo ",       "revenue": "61000",     "currency": "NOK", "covers": "140", "rating": None},
    {"restaurant": "Pasta Palace",    "city": "Stockholm",  "revenue": "182000",    "currency": "SEK", "covers": "210", "rating": "4.5"},
    {"restaurant": "Green Garden",    "city": "Oslo",       "revenue": "see notes", "currency": "NOK", "covers": "88",  "rating": "4.1  "},
    {"restaurant": "Burger Barn",     "city": "Copenhagen", "revenue": "31500",     "currency": "DKK", "covers": "210", "rating": "6.0"},
    {"restaurant": "  Ramen House ",  "city": "Stockholm",  "revenue": "74000",     "currency": "SEK", "covers": None,  "rating": "4.2"},
]

raw = pd.DataFrame(raw_data)
raw

#### 5a. Fix restaurant names

In pandas: `Series.str` — a string accessor that applies string methods to every value at once.

In [ ]:
# .str.strip() removes leading/trailing whitespace from every value
# .str.title() applies title case to every value
# Chain them together — just like chaining string methods in Python

raw["restaurant"] = raw["restaurant"].str.strip().str.title()
raw["restaurant"]

# Compare to function written with built-ins:
# def clean_name(name):
#     return name.strip().title()
# [clean_name(r["restaurant"]) for r in raw_data]

#### About method chaining

The above method chaining is very useful and concise. However, when it becomes too long, it will be hard to read. 

Therefore, below code formatting makes the chaining easier to read. But it is important to test your code so the breaks are correct wrapped without breaking code.

In [ ]:
# An alternative way to chain methods

raw["restaurant"] = (raw["restaurant"]
                    #comment
                    .str.strip()
                    #comment
                    .str.capitalize())

raw["restaurant"]

#### 5b. Convert revenue to numeric

In earlier lecture, we used: `parse_number()` — `try/except` around `float(value)`  
In pandas: `pd.to_numeric()` with `errors='coerce'` — bad values become `NaN` automatically.

In [ ]:
# check data types before cleansing

raw[["revenue", "covers", "rating"]].dtypes

In [ ]:
# errors='coerce' turns anything that can't be converted into NaN
# 'see notes' becomes NaN — no try/except needed

raw["revenue"] = pd.to_numeric(raw["revenue"], errors="coerce")
raw["covers"]  = pd.to_numeric(raw["covers"],  errors="coerce")
raw["rating"]  = pd.to_numeric(raw["rating"],  errors="coerce")

In [ ]:
# After cleansing

raw[["revenue", "covers", "rating"]].dtypes

In [ ]:
raw[["revenue", "covers", "rating"]]

#### 5c. Handle missing values

In earlier lecture: `if value is None: return default`  
In pandas: `.fillna()` to replace NaN with a default, or `.dropna()` to remove rows with missing values.

In [ ]:
# Replace NaN revenue with 0 (same default we used in parse_number)
raw["revenue"] = raw["revenue"].fillna(0)

raw[["revenue", "rating"]]

In [ ]:
# For rating: cap values above 5.0 — then leave NaN as-is (no valid rating to fall back on)
raw["rating"] = raw["rating"].clip(upper=5.0)

# Observe row index 6
raw[["revenue", "rating"]]

#### 5d. Remove duplicates

In pandas: `.drop_duplicates()` — one line.

In [ ]:
# After cleansing, below rows appear to be identical

raw.iloc[[0,4]]

In [ ]:
# Keep first occurrence

raw = raw.drop_duplicates(subset=["restaurant", "city", "revenue", "currency", "covers","rating"], keep="first")

In [ ]:
# After dedup

raw

## TO BE CONTINUED 🐍

>I tried to write a joke about Pandas... <br>
>*but it only worked in a DataFrame of mind.*

## To Explore After Lecture

- Package `ydata-profiling`: https://www.datacamp.com/tutorial/pandas-profiling-ydata-profiling-in-python-guide
- W15 Reference - Kaggle
- Good to re-read and practice: concept of relative path shown in W14/14.2.1 1D data the way Python sees it and BI use cases.ipynb

# Lecture 6 - Data Workflow & Automation

Today we will continue with pandas basics. And then take a look a small example of data workflow that simulates a data pipeline and it can be automated further to handle tasks repetitively.

## Pandas Basics - Part 2

First, we continue with pandas basics.

**What we'll cover:**

1. Adding columns
7. Filtering rows
8. Grouping and aggregating
9.  Sorting
10. Date & Time

### Recap - pandas Basics Part 1

1. The two core pandas objects: `Series` (1D) and `DataFrame` (2D)
   - One row from a `DataFrame` is a `Series`
   - One column from a `DataFrame` is also a `Series`
   - One cell sometimes is referred as an element in pandas documentation. 
2. Loading data — from a dict, CSV, and Excel
   - We created a DataFrame by input a <font color=Lime> clean </font> restaurant dataset with code
   - pd.to_csv() the DataFrame to a data folder with relative path
   - pd.read_csv() to import the data again.
3. Inspecting a DataFrame with methods.
4. Selecting columns and rows.
   - Column: think basic data types dictionary and list
   - Row : loc or iloc [row]
   - Cell: loc or iloc [row, column]
5. Cleaning data — the pandas way
   - We created a DataFrame with <font color=Fuchsia> raw </font> data

Let's pick it up from here.

In [ ]:
# raw (dirty) dataset from 5 cleaning data - the pandas way

import pandas as pd

# Raw data
raw_data = [
    {"restaurant": "  pasta palace   ",  "city": "Stockholm",  "revenue": "182000",    "currency": "SEK", "covers": "210", "rating": "4.5"},
    {"restaurant": "Burger Barn  ",   "city": "Stockholm",  "revenue": "95000",     "currency": "SEK", "covers": "180", "rating": "3.8"},
    {"restaurant": "SUSHI SPOT",      "city": "Copenhagen", "revenue": "28000",     "currency": "DKK", "covers": "95",  "rating": "4.9"},
    {"restaurant": "taco town",       "city": " Oslo ",       "revenue": "61000",     "currency": "NOK", "covers": "140", "rating": None},
    {"restaurant": "Pasta Palace",    "city": "Stockholm",  "revenue": "182000",    "currency": "SEK", "covers": "210", "rating": "4.5"},
    {"restaurant": "Green Garden",    "city": "Oslo",       "revenue": "see notes", "currency": "NOK", "covers": "88",  "rating": "4.1  "},
    {"restaurant": "Burger Barn",     "city": "Copenhagen", "revenue": "31500",     "currency": "DKK", "covers": "210", "rating": "6.0"},
    {"restaurant": "  Ramen House ",  "city": "Stockholm",  "revenue": "74000",     "currency": "SEK", "covers": None,  "rating": "4.2"},
]

raw = pd.DataFrame(raw_data)

In [ ]:
raw.to_csv("data/restaurants_raw.csv", index=False)

### Inpect Raw Data

This DataFrame has no numeric columns before cleansing.

In [ ]:
# 3. inpect a DataFrame (exploratory data analysis - EDA)

print("Shape:", raw.shape)

print("\nColumns:")
print(raw.dtypes)

print("\n--- first (3) rows ---")
print(raw.head(3))

print("\n--- last (3) rows ---")
print(raw.tail(3))

In [ ]:
# compare ouptut here with lecture 5's clean.describe()
# TODO: read help(pd.DataFrame.describe)

print("\n--- Summary when all columns are strings ---")
print()
print(raw.describe())

print("\n--- Missing values: ---")
print(raw.isna().sum())

# Show data side by side for easy reading
raw

### Introducing `pandas.DataFrame.copy` 

Suppose that we are assisting larger and more complex data projects where we will perform exploration, analysis, data modeling (as for database, data warehouse, lakehouse etc.) *BEFORE* or *WHILE* the solution designs are taking place. During these processes, it helps to simulate how the data will be carried through later on in production - therefore, *HOW* we do sometimes can simulate an actual data workflow that later on getting scaled up for implementation and deployment. 

> **BEFORE** as often referred as *from 0 to 1*. <br>
> **WHILE** as actual agile development is happening in contrast of more traditional waterfall method. <br>
> **HOW** here can be referred as design-led product thinking and test-driven development, meaning we disect larger problems to manageable and **verifiable** smaller pieces to prototype in order to understand both the problems and the solutions better. 

We had a glimpse upon a mini example of such data workflow in lecture 3 (Week 14: 14.1 Control flow - A first look at data workflow, W14 Reference - a data workflow). Python is quite suitable for this type of work - I hope by now you have built your early understanding how this might work with code interacting with physical data at your finger tips. 

Keeping the above in mind, we will now adjust how 5. cleaning data - the pandas way will be carried out: **we will isolate the raw data from its downstream transformation** - a bit like how we are treating bronze to silver layer transformation in the medallion architecture. Remember when we drew on a whiteboard and compared to the mini data workflow example? If not, read [what is the medallion lakehouse architecture](https://learn.microsoft.com/en-us/azure/databricks/lakehouse/medallion) for more info.

With pandas, we simulate the bronze to silver layer transformation by starting with ``pandas.DataFrame.copy`` method. 

There is another reason besides data workflow good practice to warrant an indepth introduction for a *mere copy* method. 

This is because Python's native *copy* behavior works quite surprisingly different. Read this Medium article about [understanding variable assignment, shallow copy and deep copy in Python: explained for beginners](https://medium.com/@send2anshup/understanding-variable-assignment-shallow-copy-and-deep-copy-in-python-explained-for-beginners-c275fc4def95). The article also explained a few real-world example how these default features are needed for and used.

For us, we will take pandas copy method, which by default is ``deepcopy``. Run help to read for yourself. Below are quoted from ``help(pd.DataFrame.copy)``:

>Help on function copy in module pandas.core.generic:
>
>copy(self, deep: bool = True) -> Self<br>
>&emsp; Make a copy of this object's indices and data.<br>
>
>&emsp; When ``deep=True`` (default), a new object will be created with  <br>
>&emsp; a copyof the calling object's data and indices. <br>
>&emsp; <font color=lime> Modifications </font> to the data or indices of the copy <br>
>&emsp; will <font color=lime> not be reflected </font> in the <font color=lime> original object </font> (see notes below).

So, let's get to it.

In [ ]:
# this is a variable assignment pointing to the same underlying object
# does not isolate raw from raw_1 (an example name for transformation 1)

raw_1 = raw

# make some changes to raw_1 now and call both to compare output

In [3]:
# this is a pandas.DataFrame.copy
# now that raw must be a DataFrame object to "trigger" pandas copy method. A list copy for example is a Python default shallow copy

raw_1 = raw.copy()

### 5. Cleansing data with `map` and `apply`

Compare below with lecture 5 same section. Do you see how they differ?

In [4]:
# 5a. fix multiple string columns

raw_1[["restaurant", "city"]] = (raw_1[["restaurant", "city"]]
                                   .map(lambda x: x.strip().capitalize()))

# 5b & 5c. convert to numeric with apply and chain in fillna for missing data

raw_1[["revenue","covers"]] = (raw_1[["revenue","covers"]]
                               .apply(pd.to_numeric,errors="coerce")
                               .fillna(0))

# 5b & 5c. convert to numeric and handle irregular values
# Rating with NaN is probably meaningful for this business case. Here we choose to keep it as such instead of replacing with 0.

raw_1["rating"]  = (pd.to_numeric(raw_1["rating"],  errors="coerce")
                    .clip(upper=5.0))

# 5d: dedup when certain they are duplicates

raw_1 = raw_1.drop_duplicates(subset=["restaurant", "city"], keep="first")

raw_1

     restaurant        city   revenue currency  covers  rating
0  Pasta palace   Stockholm  182000.0      SEK   210.0     4.5
1   Burger barn   Stockholm   95000.0      SEK   180.0     3.8
2    Sushi spot  Copenhagen   28000.0      DKK    95.0     4.9
3     Taco town        Oslo   61000.0      NOK   140.0     NaN
5  Green garden        Oslo       0.0      NOK    88.0     4.1
6   Burger barn  Copenhagen   31500.0      DKK   210.0     5.0
7   Ramen house   Stockholm   74000.0      SEK     0.0     4.2

In [ ]:
# Compare to raw

raw

### Pandas Function Application

>Quoted from pandas documentation **function application**: to apply your own or another library’s functions to pandas objects, you should be aware of the three methods below. The appropriate method to use depends on whether your function expects to operate on an entire ``DataFrame`` or ``Series``, row- or column-wise, or elementwise.

- Applying Elementwise (cell) Functions: ``map()``
- Row or Column-wise Function Application: ``apply()``
- Tablewise Function Application: ``pipe()``

The official documentation is actually one of the best sources to read and learn about them. Please visit page: https://pandas.pydata.org/pandas-docs/dev/user_guide/basics.html#function-application

We have a few examples so it's earlier for you to relate to the docs.

### A Refresher on Jupyter Variables

In lecture 1 (13.1.2 Python basics - The four building blocks), we introduced  variables. ALso how to list all, delete specific one or multiple variables. Now it's good time to revisit that section.

In addition, we can also use an area we haven't been using so often: terminal > JUPYTER VARIABLES. 

Toggle your terminal and find JUPYTER to have a look now. 

We will keep an eye on this this when we start to transform the dataset.

### 6. Adding columns

If prefered, now can be good time to create next copy to isolate cleansing phase from transformation, such as adding columns or removing columns. Depending on the data warehouse or lakehouse architecture principle, this phase can be considered silver layer engineering work. 

Don't worry if you are uncertain at the moment. The rule of thumb is to keep your own workflow easy to understand, debug and improve. 

In compex projects, it normally becomes quite natural where to break and set next variable before continue. In SQL, complex transformation sometimes contain multiple temporary tables organized like a hand-over chain in one script to perform what we do here. This is a comparable approach as we do here - while we work almost like a "sandbox" style with Python and Jupyter Notebook.

In [5]:
raw_2 = raw_1.copy()

Next, we want to convert revenues to the same currency SEK. We do so by adding two columns by adding a calcuated SEK amount as a new column.

In [6]:
# For currency conversion we create a FX (foreign exchange) dictionary - a simple mapping table.

EXCHANGE_RATES = {"SEK": 1.0, "DKK": 1.45, "NOK": 0.98}

# new column with FX rate
raw_2["rate"] = raw_2["currency"].map(EXCHANGE_RATES)

# new calculated column for revenue in SEK
raw_2["revenue_sek"] = raw_2["revenue"] * raw_2["rate"]

raw_2

,restaurant,city,revenue,currency,covers,rating,rate,revenue_sek
0,Pasta palace,Stockholm,182000.0,SEK,210.0,4.5,1.00,182000.0
1,Burger barn,Stockholm,95000.0,SEK,180.0,3.8,1.00,95000.0
2,Sushi spot,Copenhagen,28000.0,DKK,95.0,4.9,1.45,40600.0
3,Taco town,Oslo,61000.0,NOK,140.0,NaN,0.98,59780.0
5,Green garden,Oslo,0.0,NOK,88.0,4.1,0.98,0.0
6,Burger barn,Copenhagen,31500.0,DKK,210.0,5.0,1.45,45675.0
7,Ramen house,Stockholm,74000.0,SEK,0.0,4.2,1.00,74000.0

In [7]:
# New column revenue per cover — pandas handles division column-by-column
# Where covers is NaN or 0, the result is NaN automatically (no ZeroDivisionError)

raw_2["rev_per_cover"] = (raw_2["revenue_sek"] / raw_2["covers"]).round(1)

For the next new column revenue_tier, we want to label rows (restaurants) based on the size of revenue. We will look at three alternative ways to get this done.

In [ ]:
# Option 1: the pandas native pandas.cut function

# first without label the range (interval)
raw_2["revenue_tier"] = pd.cut(raw_2["revenue_sek"],
                               bins=[0, 50000, 100000, float("inf")]
                               )
raw_2

In [8]:
# clearly labeled

raw_2["revenue_tier"] = pd.cut(raw_2["revenue_sek"],
                               bins=[-float("inf"), 50000, 100000, float("inf")],
                               labels=["Low", "Medium", "High"])

raw_2

,restaurant,city,revenue,currency,covers,rating,rate,revenue_sek,rev_per_cover,revenue_tier
0,Pasta palace,Stockholm,182000.0,SEK,210.0,4.5,1.00,182000.0,866.7,High
1,Burger barn,Stockholm,95000.0,SEK,180.0,3.8,1.00,95000.0,527.8,Medium
2,Sushi spot,Copenhagen,28000.0,DKK,95.0,4.9,1.45,40600.0,427.4,Low
3,Taco town,Oslo,61000.0,NOK,140.0,NaN,0.98,59780.0,427.0,Medium
5,Green garden,Oslo,0.0,NOK,88.0,4.1,0.98,0.0,0.0,Low
6,Burger barn,Copenhagen,31500.0,DKK,210.0,5.0,1.45,45675.0,217.5,Low
7,Ramen house,Stockholm,74000.0,SEK,0.0,4.2,1.00,74000.0,inf,Medium

In [ ]:
# What is float("inf")? Try remove float("inf") or replace it with say 120000 and see what happens.

raw_2["revenue_tier"] = pd.cut(raw_2["revenue_sek"],
                               bins=[0, 50000, 100000, 120000],
                               labels=["Low", "Medium", "High"])

raw_2

In [ ]:
# Option 2: a custom function AND .apply()

def revenue_tier(rev):
    if rev >= 100000:
        return "High"
    elif rev >= 50000:
        return "Medium"
    else:
        return "Low"

raw_2["tier"] = raw_2["revenue_sek"].apply(revenue_tier)

In [ ]:
# Option 3: with a lambda and .apply. 

# below can be written in one line. I personally find it hard to read - but maybe it works after seeing it often:) I reformatted the code, slightly easier to read.

# raw_2["tier"] = raw_2["revenue_sek"].apply(lambda x:"High" if x >= 100000 else "Medium" if x >= 50000  else "Low")

raw_2["tier"] = (raw_2["revenue_sek"]
                 .apply(lambda x: 
                        "High" if x >= 100000 
                        else "Medium" if x >= 50000 
                        else "Low"))

### 7. Filtering Rows & Boolean Indexing

In 2. Inspect a DataFrame, we have seen isna()

In [ ]:
raw_2.isna()

This boolean method is used for filtering rows quickly in DataFrame. This functionality is also called **boolean masking** or **boolean indexing**: when the condition is met (True/False), filter rows.

> The syntax maps directly to SQL `WHERE` clauses.

In [ ]:
raw_2[raw_2["revenue_sek"] > 50000]

In [ ]:
raw_2[raw_2["city"] == "Stockholm"]

In [ ]:
# Combine conditions with & (and) and | (or)
# Note: use parentheses around each condition — Python operator precedence requires it

# Stockholm restaurants with revenue above 80 000 SEK
raw_2[(raw_2["city"] == "Stockholm") & (raw_2["revenue_sek"] > 80000)]

In [ ]:
# Filter out rows where rating is missing
# .notna() is the opposite of .isna()

raw_2[raw_2["rating"].notna()]

## BREAK TIME 🐍

>Why did the data analyst break up with the automation script?<br>
>*It kept running without her.*

### 8. Grouping and aggregating `groupby`

> In short: this is the DataFrame equivalent of SQL `GROUP BY`.

In [ ]:
raw_2.groupby("city")["revenue_sek"].sum()

In [ ]:
type(raw_2.groupby("city")["revenue_sek"].sum())

In [ ]:
raw_2.groupby("city")["revenue_sek"].sum().index

In [ ]:
# If I want to create a new DataFrame out of the above Series

# Option 1: Directly in groupby() but specify as_index=False tells groupby to not make city the index, returning a DataFrame directly.

city_revenue = (raw_2
                .groupby("city", as_index=False)["revenue_sek"]
                .sum())

city_revenue

In [ ]:
# Option 2: use reset_index as a chain

city_revenue_2 = (raw_2
                .groupby("city")["revenue_sek"]
                .sum()
                .reset_index())

city_revenue_2

In [ ]:
# Option 3: to_frame()

city_revenue_3 = (raw_2.groupby("city")["revenue_sek"]
                .sum()
                .to_frame())
city_revenue_3

# this use city as index - if you'd like that

In [ ]:
del city_revenue_2, city_revenue_3

### Now We Have Pivot Table

In [ ]:
# If we add more columns to group by to aggregate several columns, we got a variation of pivot table.

raw_2.groupby(["city","currency"])[["revenue_sek","covers"]].sum()

In [ ]:
# Another pivot table

raw_2.pivot_table(index="city", 
                  columns="revenue_tier",
                  values="rating",
                  aggfunc="count")

In [ ]:
# I wanted to show the revenue_tier in reversed order and found out I had to do this. There is no way I will remember the iloc...

raw_2.pivot_table(index="city", 
                  columns="revenue_tier",
                  values="rating",
                  aggfunc="count").iloc[:, ::-1]

In [ ]:
# Then perhaps we do this instead:

def reverse_columns(df):
    return df.iloc[:, ::-1]

In [ ]:
# Can we chain it?

raw_2.pivot_table(index="city", 
                  columns="revenue_tier",
                  values="rating",
                  aggfunc="count").reverse_columns

In [ ]:
# pipe is called for

city_revenue_tier = (raw_2
                     .pivot_table(index="city", 
                                  columns="revenue_tier",
                                  values="rating",
                                  aggfunc="count",
                                  fill_value=0)
                     .pipe(reverse_columns))

city_revenue_tier

### 9. Sorting

In [ ]:
# Simple sort

raw_2.sort_values("revenue_sek", ascending=False)

In [ ]:
# Subset multiple columns, sort by one of selected columns
 
raw_2.sort_values("revenue_sek", ascending=False)[["restaurant", "city", "revenue_sek", "revenue_tier"]]

In [ ]:
# Subset multiple columns, sort by multiple columns

raw_2.sort_values(["city", "revenue_sek"], ascending=[True, False])[["restaurant", "city", "revenue_sek"]]

### 10. Date & Time

Below are some handy functions for date and time. There are a lot more to learn and practice about date and time.

In [ ]:
import pandas as pd

df_raw = pd.DataFrame({
    "event": ["A", "B", "C", "D", "E", "F"],
    "date": ["2025-01-15", "2025-06-20", "2025-11-03",
             "2025-03-08", "2025-09-12", "2025-12-24"],
    "date_to_clean": ["15/01/2025", "20-06-2025", "Nov 03 2025",
                      "08.03.2025", "12 Sep 2025", "24/12/2025"],
    "time": ["08:30", "13:45", "17:00",
             "09:15", "14:30", "18:45"]
})

df_raw

In [ ]:
df_raw.dtypes

In [ ]:
df_raw.describe()

#### 1. Parsing dates

In [ ]:
df = df_raw.copy()

# date column is already in standard format — straightforward
df["date"] = pd.to_datetime(df["date"])

df.dtypes

In [ ]:
# date_to_clean has mixed formats — pandas infers automatically

df["date_to_clean"] = pd.to_datetime(df["date_to_clean"], format="mixed", dayfirst=True)

df.dtypes

In [ ]:
df

#### 2. Formatting

Read [Python documentation: `strftime()` and `strptime()` format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) to try out the format you need.

In [ ]:
# Convert to a specific string format for display or export

df["date_formatted"] = df["date"].dt.strftime("%d %B %Y")
# 2025-01-15 → "15 January 2025"

df

In [ ]:
df["date_formatted"].dtypes

#### 3. Simple date calculations

In [ ]:
df["eom"] = df["date"] + pd.offsets.MonthEnd(0)
df["eoq"] = df["date"] + pd.offsets.QuarterEnd(0)
df["eoy"] = df["date"] + pd.offsets.YearEnd(0)

In [ ]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day

In [ ]:
df

In [ ]:
df_subset = df[["event", "date", "year","month","day","time","eoy"]]

df_subset

In [ ]:
# How many days until end of year? Here is days remaining after today.

df_subset["days_until_eoy"] = ( df["eoy"] - df["date"]).dt.days

df_subset["days_until_next_eoy"] = (pd.Timestamp("2026-12-31") - df["date"]).dt.days

df_subset

In [ ]:
df_subset = df_subset.drop(columns=["days_until_next_eoy"])

#### 4. Conditional date range — subsetting

In [ ]:
# Filter rows between two dates

df_subset[df_subset["date"].between("2025-01-01", "2025-06-30")]

#### 5. Timestamp

In [ ]:
# Combine date and time columns into one timestamp — needs both columns, so axis=1

df_subset["timestamp"] = df_subset.apply(lambda row: 
                           pd.Timestamp(f"{row['date'].date()} {row['time']}"), axis=1)

df_subset

In [ ]:
# Add a timestamp now

df_subset["processed_at"] = pd.Timestamp.now().strftime("%y%m%d_%H%M%S")

In [ ]:
df_subset

In [ ]:
df_subset.dtypes

### Saving results

Once the data is clean and analysed, it's ready to be saved — to the storage chosen.

In [ ]:
clean = raw_2.copy()

# Subset to Keep needed columns if desire so
output_cols = ["restaurant", "city", "revenue_sek", "covers", "rev_per_cover", "rating", "revenue_tier"]
result = clean[output_cols].sort_values("revenue_sek", ascending=False)

# Save to CSV
result.to_csv("restaurants_clean.csv", index=False)
print("Saved to restaurants_clean.csv")

# Save to Excel
result.to_excel("restaurants_clean.xlsx", sheet_name="Clean Data", index=False)
print("Saved to restaurants_clean.xlsx")

In [ ]:
# Final result — what we would hand to the report
result

## BREAK TIME 🐍

>Why did the data pipeline go to therapy?<br>
>*Too many bottlenecks.*

## Simulate Data Pipeline

Now we have actually a few new variables. They are tiny and just representations of what we now can use pandas for. 

If we look at the terminal JUPYTER VARIABLES, let's organize them as they are travelling through a medallion architecture:

- source data: raw_data
- bronze layer: raw
- silve/gold layer: raw_2, city_revenue, city_revenue_tier, EXCHANGE_RATE

The silver/gold layer are combined here because different lakehouse design guidlelines might be followed at your work place. Different complexity in projects sometimes also require specific solutions. 

If we put the above into Python scripts to simulate how these steps can work.

In [ ]:
from pathlib import Path

Path.cwd()

In [ ]:
# This can also be run in temrinal.

%run pipeline/run_pipeline.py

In [ ]:
#list(steps)

## Work in a More Pythonic Way

In [ ]:
import sys
import pandas as pd

# To point out where the .py script is stored
# Run ``sys.path`` to see what it contains and what data type the output is.

# below represents scripts/folder
sys.path.append("scripts")
# .append is to add a string to the existing``sys.path``.
# Now it points to scripts folder, where the pipeline_pythonic.py code is stored.

from pipeline_pythonic import load, clean, transform, publish

# Step by step so you can inspect each stage

# In function load(str), the path in string is relative to your notebook's relative path. Therefore, it points to data/ folder
# It has nothing to do with where the above .py script is.
# The custom (user-defined) functions have been imported into in-momery. You can run help(load) to see it.

raw       = load("data/restaurants_raw.csv")
cleaned   = clean(raw)
result    = transform(cleaned)

# output/ here is the 3rd folder path we see in this run .py code block. 
# it points to the output folder.
# all 3 folders we see here are at the same level
publish(result, "output/restaurants_clean.csv")

✓ Loaded 8 rows from data/restaurants_raw.csv
✓ Published 7 rows → output/restaurants_clean.csv

### `assign()` & New Columns

This is one frequently used DataFrame method when chaining up DataFrame in user-defined functions. When used together with `lambda`, it's convenient to create multiple new columns.

The official doc is also very good on this one: https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.assign.html#pandas.DataFrame.assign

## The Official Pandas Cheat Sheet

There are a lot more useful pandas functions and methods. Above are just a small portion of it. Please do read Wes's book, pandas official doc and of course [Data Wrangling with pandas Cheat Sheet (PDF)](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf).

## Good-to-knows about Scripts

The scripts and workflows we have in our lectures are intentionally created for learning purpose during Nackademin' BI25 - BI-relaterade programspråk. They do not reflect any actual data workflow and they may not uphold to the standard required for Python projects in production.

## END OF LECTURE 🐍

Have a great weekend and see you on Monday!

# Python Regex for Beginners

A friendly guide based on the [official Python docs](https://docs.python.org/3/howto/regex.html)

## What is Regex?

A **regular expression** (regex) is a pattern you use to search for text. Think of it like a super-powered "Find" tool.

For example:
- Find all phone numbers in a document
- Check if an email address looks valid
- Pull all dates out of a log file

In Python, regex is available through the **built-in `re` module**. Run the cell below to import it — you'll need this in every session!

In [ ]:
import re  # The re module is built into Python — no install needed.

## Simple Patterns

The simplest regex is just the text you want to find. The pattern `cat` matches the word `cat` exactly.

`re.search()` returns a **match object** if found, or `None` if not. Try both cells below:

In [ ]:
# This should find a match
result = re.search("cat", "I have a cat")
print(result)

In [ ]:
# ❌ This should return None (no match)
result = re.search("cat", "I have a dog")
print(result)

## Special characters (metacharacters)

Some characters have special meaning in regex — they are **not** matched literally:

. ^ $ * + ? { } [ ] \ | ( )

We'll cover the most important ones below.

## Raw string `r""`

Before we go further — this is the **#1 tip for beginners**.

Always prefix your regex pattern with `r`. This tells Python not to treat backslashes (`\`) specially, which avoids a lot of confusing bugs.

In [ ]:
# Always do this instead — the r prefix makes it a "raw string"
result = re.search(r"\d", "room 42")
print(result)

# ❌ Avoid this — can cause unexpected behaviour
re.search("\d", "room 42")

## Character Classes `[ ]`

Square brackets let you match **one character from a set**.

| Pattern | Matches |
|---------|--------|
| `[abc]` | Any one of: `a`, `b`, or `c` |
| `[a-z]` | Any lowercase letter |
| `[A-Z]` | Any uppercase letter |
| `[0-9]` | Any digit |
| `[^abc]` | Anything **except** `a`, `b`, or `c` |

<br>
The `^` inside brackets means "NOT".

In [ ]:
# Match any vowel
m = re.search(r"[aeiou]", "hello")
print(m.group())  # 'e' — the first vowel found

In [ ]:
# Match any digit
m = re.search(r"[0-9]", "room 42")
print(m.group())  # '4'

In [ ]:
# Try it yourself! Change the pattern or text and see what matches.
my_pattern = r"[A-Z]"
my_text = "Hello World"

m = re.search(my_pattern, my_text)
print(m.group() if m else "No match")

## Handy Shortcut Sequences

Instead of writing `[0-9]` every time, Python offers shortcuts:

| Shortcut | Meaning | Same as |
|----------|---------|--------|
| `\d` | Any digit | `[0-9]` |
| `\D` | Any non-digit | `[^0-9]` |
| `\w` | Any letter, digit, or underscore | `[a-zA-Z0-9_]` |
| `\W` | Any non-word character | `[^a-zA-Z0-9_]` |
| `\s` | Any whitespace (space, tab, newline) | `[ \t\n\r]` |
| `\S` | Any non-whitespace | `[^ \t\n\r]` |
| `.` | Any character except newline | — |

In [ ]:
print(re.search(r"\d", "I am 25 years old").group())  # '2'
print(re.search(r"\w", "Hello!").group())              # 'H'
print(re.search(r"\s", "Hello World").group())         # ' ' (a space)

## Repeating Things (Quantifiers)

What if you want to match more than one character?

| Symbol | Meaning | Example | Matches |
|--------|---------|---------|--------|
| `*` | 0 or more times | `ca*t` | `ct`, `cat`, `caaat` |
| `+` | 1 or more times | `ca+t` | `cat`, `caaat` (not `ct`) |
| `?` | 0 or 1 time (optional) | `colou?r` | `color`, `colour` |
| `{n}` | Exactly n times | `\d{4}` | `2024` |
| `{m,n}` | Between m and n times | `\d{2,4}` | `12`, `123`, `1234` |

In [ ]:
# * means zero or more — so 'ct' still matches ca*t
print(re.search(r"ca*t", "ct").group())     # 'ct'
print(re.search(r"ca*t", "caaat").group())  # 'caaat'

In [ ]:
# + means one or more — 'ct' does NOT match ca+t
print(re.search(r"ca+t", "ct"))      # None
print(re.search(r"ca+t", "cat").group())  # 'cat'

In [ ]:
# ? makes something optional
print(re.search(r"colou?r", "color").group())   # 'color'
print(re.search(r"colou?r", "colour").group())  # 'colour'

In [ ]:
# {n} matches exactly n times
print(re.search(r"\d{4}", "Year: 2024").group())  # '2024'

## The 4 Main Functions

### `re.search()` — Find the first match *anywhere* in the string

In [ ]:
text = "I have 2 cats and 3 dogs"

m = re.search(r"\d", text)
print(m.group())  # '2' — first digit found

### `re.match()` — Only checks the very *beginning* of the string

In [ ]:
print(re.match(r"\d", "I have 2 cats"))  # None — doesn't start with a digit
print(re.match(r"\d", "42 cats").group())  # '4' — starts with a digit ✅

### `re.findall()` — Returns a *list* of all matches

In [ ]:
text = "I have 2 cats and 3 dogs"

numbers = re.findall(r"\d", text)
print(numbers)  # ['2', '3']

### `re.sub()` — Find and *replace*

In [ ]:
text = "I have 2 cats and 3 dogs"

result = re.sub(r"\d", "X", text)
print(result)  # 'I have X cats and X dogs'

## Checking for a Match Safely

`search()` returns `None` if nothing is found. Calling `.group()` on `None` will crash your code! Always check first:

In [ ]:
m = re.search(r"\d+", "room 42")

if m:
    print("Found:", m.group())   # Found: 42
else:
    print("No match")

## Match Object Methods

When you get a match, you can ask it for details:

In [ ]:
m = re.search(r"\d+", "room 42")

print(m.group())   # '42'    — the matched text
print(m.start())   # 5       — where the match starts
print(m.end())     # 7       — where it ends
print(m.span())    # (5, 7)  — start and end as a tuple

## Useful Flags

Flags tweak how matching works. Pass them as a second argument:

| Flag | Short | What it does |
|------|-------|--------------|
| `re.IGNORECASE` | `re.I` | Case-insensitive matching |
| `re.MULTILINE` | `re.M` | `^` and `$` match each line, not just the whole string |
| `re.DOTALL` | `re.S` | `.` also matches newline characters |

In [ ]:
# Without flag — case sensitive, no match
print(re.search(r"hello", "HELLO WORLD"))  # None

# With IGNORECASE flag — matches!
print(re.search(r"hello", "HELLO WORLD", re.IGNORECASE).group())  # 'HELLO'

## Example: Find Email Addresses

In [ ]:
text = "Contact us at hello@example.com or support@company.org"

emails = re.findall(r"\w+@\w+\.\w+", text)
print(emails)

# ['hello@example.com', 'support@company.org']

## Sandbox — Try Your Own Patterns!

Use this cell to experiment freely. Change the pattern and text to test what you've learned.

In [ ]:
my_pattern = r"\d+"                              # 👈 Change this
my_text    = "Order #1042 placed on 2024-03-15"  # 👈 And this

# Find first match
m = re.search(my_pattern, my_text)
print("First match :", m.group() if m else "No match")

# Find all matches
all_matches = re.findall(my_pattern, my_text)
print("All matches :", all_matches)

# Reference - A Data Workflow in Narrative

## What's this narrative?

For learning purpose, let's describe step by step what we try to do with the dataset.

## What we do here differs from lecture 3 notes?

We want to be sure that no rows are dropped from the dataset even if there is None (null values) in some rows.

## 1. Raw data ingestion (generation)

In [ ]:
raw_data = [
    {"region": "North", "product": "Widget A", "revenue": "120000", "cost": "80000"},
    {"region": "South", "product": "Widget B", "revenue": "85000",  "cost": "60000"},
    {"region": "North", "product": "Widget C", "revenue": None,     "cost": "40000"},
    {"region": "East",  "product": "Widget A", "revenue": "200000", "cost": "130000"},
    {"region": "South", "product": "Widget C", "revenue": "30000",  "cost": "20000"},
]

## 2. Inspect data

We will learn in the future lecture how to profile data with Pandas. For now, we eye ball it. Or you can also use VSCode extension Data Wrangler.

## 3. Create cleansing function

In comments, we decribe what the code does or the logic behind. Please note this is for learning purpose. At work, you ought to be concise and write *clean* code whenever possible.

In [ ]:
# This function will go through record row by row when called for.

# function requires a single argument 'r':
def parse_record(r): 
    # __docstring__ is added
    """
    Convert revenue and cost from string to number. 
    Calculate and add new key value pairs profit and margin.
    All record with None value are replaced with 0.
    Margin is treated as 0 when revenue is 0 (None).
    """
    # Use `try / except` to catch errors gracefully instead of letting the program crash. You can catch specific exception types for precise control.
    try:
        # use a ternary expression to insert 0 if field value is None
        rev = 0 if r["revenue"] is None else float(r["revenue"])
        cost = 0 if r["cost"] is None else float(r["cost"])
        # return dicts containing below key and value pairs
        return {
            "region":  r["region"],
            "product": r["product"],
            "revenue": rev,
            "cost":    cost,
            # new keys profit and margin are added
            "profit":  rev - cost,
            # if revenue is 0, margin would show ZeroDivisionError. We let the roll level margin be 0 for these.
            "margin":  0 if rev == 0 else round((rev - cost) / rev, 2) 
        }
    # the`try / except` behaves like second defence if the above logic didn't catch all the messy data
    except (TypeError, ValueError):
        return None   # skip rows with missing/bad data if they are not caught in the above

In [ ]:
# to show function's docstring
help(parse_record)

In [ ]:
# to see function's source code
parse_record??

## 4. Create clean dataset

In [13]:
# use list comprehension to clean each row of record
clean = [parse_record(r) for r in raw_data]

In [ ]:
# if needed, view data with index
for i, v in enumerate(clean):
    print(i,v)

0 {'region': 'North', 'product': 'Widget A', 'revenue': 120000.0, 'cost': 80000.0, 'profit': 40000.0, 'margin': 0.33}
1 {'region': 'South', 'product': 'Widget B', 'revenue': 85000.0, 'cost': 60000.0, 'profit': 25000.0, 'margin': 0.29}
2 {'region': 'North', 'product': 'Widget C', 'revenue': 0, 'cost': 40000.0, 'profit': -40000.0, 'margin': 0}
3 {'region': 'East', 'product': 'Widget A', 'revenue': 200000.0, 'cost': 130000.0, 'profit': 70000.0, 'margin': 0.35}
4 {'region': 'South', 'product': 'Widget C', 'revenue': 30000.0, 'cost': 20000.0, 'profit': 10000.0, 'margin': 0.33}

In [ ]:
# if needed, view data record row by row
for e in clean:
    print(e)

{'region': 'North', 'product': 'Widget A', 'revenue': 120000.0, 'cost': 80000.0, 'profit': 40000.0, 'margin': 0.33}
{'region': 'South', 'product': 'Widget B', 'revenue': 85000.0, 'cost': 60000.0, 'profit': 25000.0, 'margin': 0.29}
{'region': 'North', 'product': 'Widget C', 'revenue': 0, 'cost': 40000.0, 'profit': -40000.0, 'margin': 0}
{'region': 'East', 'product': 'Widget A', 'revenue': 200000.0, 'cost': 130000.0, 'profit': 70000.0, 'margin': 0.35}
{'region': 'South', 'product': 'Widget C', 'revenue': 30000.0, 'cost': 20000.0, 'profit': 10000.0, 'margin': 0.33}

In [ ]:
# quick row count for quality check

row_count_raw = len(raw_data)
row_count_clean = len(clean)

print(f"Before cleaning, we had {row_count_raw} rows. After cleaning we had {row_count_clean} rows. {row_count_raw - row_count_clean} is missing.")

Before cleaning, we had 5 rows. After cleaning we had 5 rows. 0 is missing.

## 5. Further analysis

In [ ]:
# --- Step 2: Filter ---
# list comprehension with condition to filter
high_margin = [r for r in clean if r["margin"] >= 0.30]
# \n insert a blank row after output
print(f"High-margin rows: {len(high_margin)}\n")

# --- Step 3: Aggregate by region ---
# set comprehension for unique record (aka distinct category)
regions = {r["region"] for r in clean}

# sorted(set) to order regions alphebetically
for region in sorted(regions):
    # list comprehension with condition to filter all rows per region
    rows = [r for r in clean if r["region"] == region]
    # generator expression to sum revenue & profit for the region's rows
    # A generator expression is a shorter and more compact way to create a generator without using a function or yield. It looks similar to a list comprehension, but uses parentheses () instead of brackets [].
    total_rev = sum(r["revenue"] for r in rows)
    total_profit = sum(r["profit"] for r in rows)
    # print formatted results
    print(f"{region:8s}  Revenue: {total_rev:>10,.0f}  Profit: {total_profit:>10,.0f}")

# --- Step 4: Top product by revenue ---
# use lambda to sort list by "revenue" in decending order
# slice index 0, which is the highest "revenue"
top = sorted(clean, key=lambda r: r["revenue"], reverse=True)[0]
# \n insert a blank row before output
print(f"\nTop product: {top['product']} in {top['region']} — {top['revenue']:,.0f}")

High-margin rows: 3

East      Revenue:    200,000  Profit:     70,000
North     Revenue:    120,000  Profit:          0
South     Revenue:    115,000  Profit:     35,000

Top product: Widget A in East — 200,000